//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HBEntities : DbContext
    {
        public HBEntities()
            : base("name=HBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientManagementHelp> ClientManagementHelps { get; set; }
        public virtual DbSet<FAdmin> FAdmins { get; set; }
        public virtual DbSet<FClientLogo> FClientLogoes { get; set; }
        public virtual DbSet<FInformation> FInformations { get; set; }
        public virtual DbSet<Mail> Mails { get; set; }
        public virtual DbSet<Paswword> Paswwords { get; set; }
        public virtual DbSet<RolesRight> RolesRights { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrRequest> TrRequests { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<WRBHBAdjustmentCategory> WRBHBAdjustmentCategories { get; set; }
        public virtual DbSet<WRBHBApartmentBookingProperty> WRBHBApartmentBookingProperties { get; set; }
        public virtual DbSet<WRBHBApartmentBookingPropertyAssingedGuest> WRBHBApartmentBookingPropertyAssingedGuests { get; set; }
        public virtual DbSet<WRBHBAPICityCode> WRBHBAPICityCodes { get; set; }
        public virtual DbSet<WRBHBAPIHeader> WRBHBAPIHeaders { get; set; }
        public virtual DbSet<WRBHBAPIHeader_FrontEnd> WRBHBAPIHeader_FrontEnd { get; set; }
        public virtual DbSet<WRBHBAPIHotelHeader> WRBHBAPIHotelHeaders { get; set; }
        public virtual DbSet<WRBHBAPIHotelHeader_FrontEnd> WRBHBAPIHotelHeader_FrontEnd { get; set; }
        public virtual DbSet<WRBHBAPIRateMealPlanInclusionDtl> WRBHBAPIRateMealPlanInclusionDtls { get; set; }
        public virtual DbSet<WRBHBAPIRateMealPlanInclusionDtls_FrontEnd> WRBHBAPIRateMealPlanInclusionDtls_FrontEnd { get; set; }
        public virtual DbSet<WRBHBAPIRoomRateDtl> WRBHBAPIRoomRateDtls { get; set; }
        public virtual DbSet<WRBHBAPIRoomRateDtls_FrontEnd> WRBHBAPIRoomRateDtls_FrontEnd { get; set; }
        public virtual DbSet<WRBHBAPIRoomTypeDtl> WRBHBAPIRoomTypeDtls { get; set; }
        public virtual DbSet<WRBHBAPIRoomTypeDtls_FrontEnd> WRBHBAPIRoomTypeDtls_FrontEnd { get; set; }
        public virtual DbSet<WRBHBAPITariffDtl> WRBHBAPITariffDtls { get; set; }
        public virtual DbSet<WRBHBAPITariffDtls_FrontEnd> WRBHBAPITariffDtls_FrontEnd { get; set; }
        public virtual DbSet<WRBHBBankAccount> WRBHBBankAccounts { get; set; }
        public virtual DbSet<WRBHBBankTransaction> WRBHBBankTransactions { get; set; }
        public virtual DbSet<WRBHBBedBookingProperty> WRBHBBedBookingProperties { get; set; }
        public virtual DbSet<WRBHBBedBookingPropertyAssingedGuest> WRBHBBedBookingPropertyAssingedGuests { get; set; }
        public virtual DbSet<WRBHBBooking> WRBHBBookings { get; set; }
        public virtual DbSet<WRBHBBookingAdvanceAmountPaid> WRBHBBookingAdvanceAmountPaids { get; set; }
        public virtual DbSet<WRBHBBookingCustomFieldsDetail> WRBHBBookingCustomFieldsDetails { get; set; }
        public virtual DbSet<WRBHBBookingGuestDetail> WRBHBBookingGuestDetails { get; set; }
        public virtual DbSet<WRBHBBookingProperty> WRBHBBookingProperties { get; set; }
        public virtual DbSet<WRBHBBookingPropertyAssingedGuest> WRBHBBookingPropertyAssingedGuests { get; set; }
        public virtual DbSet<WRBHBBookingPropertyAssingedGuest_FrontEnd> WRBHBBookingPropertyAssingedGuest_FrontEnd { get; set; }
        public virtual DbSet<WRBHBBookingTrackingPayment> WRBHBBookingTrackingPayments { get; set; }
        public virtual DbSet<WRBHBBTCSubmission> WRBHBBTCSubmissions { get; set; }
        public virtual DbSet<WRBHBBTCSubmissionCard> WRBHBBTCSubmissionCards { get; set; }
        public virtual DbSet<WRBHBBTCSubmissionCash> WRBHBBTCSubmissionCashes { get; set; }
        public virtual DbSet<WRBHBBTCSubmissionCheque> WRBHBBTCSubmissionCheques { get; set; }
        public virtual DbSet<WRBHBBTCSubmissionDetail> WRBHBBTCSubmissionDetails { get; set; }
        public virtual DbSet<WRBHBBTCSubmissionNEFT> WRBHBBTCSubmissionNEFTs { get; set; }
        public virtual DbSet<WRBHBChechkOutHdr> WRBHBChechkOutHdrs { get; set; }
        public virtual DbSet<WRBHBChechkOutPaymentCard> WRBHBChechkOutPaymentCards { get; set; }
        public virtual DbSet<WRBHBChechkOutPaymentCash> WRBHBChechkOutPaymentCashes { get; set; }
        public virtual DbSet<WRBHBChechkOutPaymentCheque> WRBHBChechkOutPaymentCheques { get; set; }
        public virtual DbSet<WRBHBChechkOutPaymentCompanyInvoice> WRBHBChechkOutPaymentCompanyInvoices { get; set; }
        public virtual DbSet<WRBHBChechkOutPaymentNEFT> WRBHBChechkOutPaymentNEFTs { get; set; }
        public virtual DbSet<WRBHBCheckInHdr> WRBHBCheckInHdrs { get; set; }
        public virtual DbSet<WRBHBCheckOutServiceDtl> WRBHBCheckOutServiceDtls { get; set; }
        public virtual DbSet<WRBHBCheckOutServiceHdr> WRBHBCheckOutServiceHdrs { get; set; }
        public virtual DbSet<WRBHBCheckOutSettleDtl> WRBHBCheckOutSettleDtls { get; set; }
        public virtual DbSet<WRBHBCheckOutSettleHdr> WRBHBCheckOutSettleHdrs { get; set; }
        public virtual DbSet<WRBHBCity> WRBHBCities { get; set; }
        public virtual DbSet<WRBHBClientColumn> WRBHBClientColumns { get; set; }
        public virtual DbSet<WRBHBClientContactType> WRBHBClientContactTypes { get; set; }
        public virtual DbSet<WRBHBClientGrade> WRBHBClientGrades { get; set; }
        public virtual DbSet<WRBHBClientGradeValue> WRBHBClientGradeValues { get; set; }
        public virtual DbSet<WRBHBClientGradeValueDetail> WRBHBClientGradeValueDetails { get; set; }
        public virtual DbSet<WRBHBClientManagement> WRBHBClientManagements { get; set; }
        public virtual DbSet<WRBHBClientManagementAddClientGuest> WRBHBClientManagementAddClientGuests { get; set; }
        public virtual DbSet<WRBHBClientManagementAddNewClient> WRBHBClientManagementAddNewClients { get; set; }
        public virtual DbSet<WRBHBClientManagementCustomField> WRBHBClientManagementCustomFields { get; set; }
        public virtual DbSet<WRBHBClientSMTP> WRBHBClientSMTPs { get; set; }
        public virtual DbSet<WRBHBClientwisePricingModel> WRBHBClientwisePricingModels { get; set; }
        public virtual DbSet<WRBHBCompanyMaster> WRBHBCompanyMasters { get; set; }
        public virtual DbSet<WRBHBContarctProductMaster> WRBHBContarctProductMasters { get; set; }
        public virtual DbSet<WRBHBContractClientPref_Details> WRBHBContractClientPref_Details { get; set; }
        public virtual DbSet<WRBHBContractClientPref_Header> WRBHBContractClientPref_Header { get; set; }
        public virtual DbSet<WRBHBContractManagement> WRBHBContractManagements { get; set; }
        public virtual DbSet<WRBHBContractManagementAppartment> WRBHBContractManagementAppartments { get; set; }
        public virtual DbSet<WRBHBContractManagementService> WRBHBContractManagementServices { get; set; }
        public virtual DbSet<WRBHBContractManagementTariffAppartment> WRBHBContractManagementTariffAppartments { get; set; }
        public virtual DbSet<WRBHBContractNonDedicated> WRBHBContractNonDedicateds { get; set; }
        public virtual DbSet<WRBHBContractNonDedicatedApartment> WRBHBContractNonDedicatedApartments { get; set; }
        public virtual DbSet<WRBHBContractNonDedicatedService> WRBHBContractNonDedicatedServices { get; set; }
        public virtual DbSet<WRBHBDeposit> WRBHBDeposits { get; set; }
        public virtual DbSet<WRBHBDepositsDlt> WRBHBDepositsDlts { get; set; }
        public virtual DbSet<WRBHBExpenseGroup> WRBHBExpenseGroups { get; set; }
        public virtual DbSet<WRBHBExpenseHead> WRBHBExpenseHeads { get; set; }
        public virtual DbSet<WRBHBExternal_Users> WRBHBExternal_Users { get; set; }
        public virtual DbSet<WRBHBExternalChechkOutTAC> WRBHBExternalChechkOutTACs { get; set; }
        public virtual DbSet<WRBHBFeedBckForm> WRBHBFeedBckForms { get; set; }
        public virtual DbSet<WRBHBFinancialYear> WRBHBFinancialYears { get; set; }
        public virtual DbSet<WRBHBGradeMaster> WRBHBGradeMasters { get; set; }
        public virtual DbSet<WRBHBImportGuest> WRBHBImportGuests { get; set; }
        public virtual DbSet<WRBHBInternal_Users> WRBHBInternal_Users { get; set; }
        public virtual DbSet<WRBHBInvoiceExternalAmount> WRBHBInvoiceExternalAmounts { get; set; }
        public virtual DbSet<WRBHBInvoiceExternalAmountMonthGenerated> WRBHBInvoiceExternalAmountMonthGenerateds { get; set; }
        public virtual DbSet<WRBHBInvoiceMaintenanceAmount> WRBHBInvoiceMaintenanceAmounts { get; set; }
        public virtual DbSet<WRBHBInvoiceManagedGHAmount> WRBHBInvoiceManagedGHAmounts { get; set; }
        public virtual DbSet<WRBHBInvoiceManagedGHAmountMonthGenerated> WRBHBInvoiceManagedGHAmountMonthGenerateds { get; set; }
        public virtual DbSet<WRBHBInvoiceRentAmount> WRBHBInvoiceRentAmounts { get; set; }
        public virtual DbSet<WRBHBInvoiceRentMonthGeneratedMaintenance> WRBHBInvoiceRentMonthGeneratedMaintenances { get; set; }
        public virtual DbSet<WRBHBInvoiceRentMonthGeneratedRent> WRBHBInvoiceRentMonthGeneratedRents { get; set; }
        public virtual DbSet<WRBHBKOTDtl> WRBHBKOTDtls { get; set; }
        public virtual DbSet<WRBHBKOTHdr> WRBHBKOTHdrs { get; set; }
        public virtual DbSet<WRBHBKOTUser> WRBHBKOTUsers { get; set; }
        public virtual DbSet<WRBHBLocality> WRBHBLocalities { get; set; }
        public virtual DbSet<WRBHBMapPOAndVendorPaymentDtl> WRBHBMapPOAndVendorPaymentDtls { get; set; }
        public virtual DbSet<WRBHBMapPOAndVendorPaymentHdr> WRBHBMapPOAndVendorPaymentHdrs { get; set; }
        public virtual DbSet<WRBHBMapVendor> WRBHBMapVendors { get; set; }
        public virtual DbSet<WRBHBMarkup> WRBHBMarkups { get; set; }
        public virtual DbSet<WRBHBMasterClientManagement> WRBHBMasterClientManagements { get; set; }
        public virtual DbSet<WRBHBMMTMarkup> WRBHBMMTMarkups { get; set; }
        public virtual DbSet<WRBHBMMTMarkupHistory> WRBHBMMTMarkupHistories { get; set; }
        public virtual DbSet<WRBHBNewPCExpenseApproval> WRBHBNewPCExpenseApprovals { get; set; }
        public virtual DbSet<WRBHBOutsourceServiceItem> WRBHBOutsourceServiceItems { get; set; }
        public virtual DbSet<WRBHBPCExpenseApproval> WRBHBPCExpenseApprovals { get; set; }
        public virtual DbSet<WRBHBPettyCash> WRBHBPettyCashes { get; set; }
        public virtual DbSet<WRBHBPettyCashApprovalDtl> WRBHBPettyCashApprovalDtls { get; set; }
        public virtual DbSet<WRBHBPettyCashHdr> WRBHBPettyCashHdrs { get; set; }
        public virtual DbSet<WRBHBPettyCashStatu> WRBHBPettyCashStatus { get; set; }
        public virtual DbSet<WRBHBPettyCashStatusHdr> WRBHBPettyCashStatusHdrs { get; set; }
        public virtual DbSet<WRBHBProperty> WRBHBProperties { get; set; }
        public virtual DbSet<WRBHBPropertyAgreement> WRBHBPropertyAgreements { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsAssociationName> WRBHBPropertyAgreementsAssociationNames { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsDetail> WRBHBPropertyAgreementsDetails { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsHistory> WRBHBPropertyAgreementsHistories { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsOwner> WRBHBPropertyAgreementsOwners { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsRoomCharge> WRBHBPropertyAgreementsRoomCharges { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsRoomChargesHistory> WRBHBPropertyAgreementsRoomChargesHistories { get; set; }
        public virtual DbSet<WRBHBPropertyAgreementsRoomType> WRBHBPropertyAgreementsRoomTypes { get; set; }
        public virtual DbSet<WRBHBPropertyApartment> WRBHBPropertyApartments { get; set; }
        public virtual DbSet<WRBHBPropertyApartmentHistory> WRBHBPropertyApartmentHistories { get; set; }
        public virtual DbSet<WRBHBPropertyBlock> WRBHBPropertyBlocks { get; set; }
        public virtual DbSet<WRBHBPropertyImage> WRBHBPropertyImages { get; set; }
        public virtual DbSet<WRBHBPropertyOwnerApartment> WRBHBPropertyOwnerApartments { get; set; }
        public virtual DbSet<WRBHBPropertyOwnerOtherContact> WRBHBPropertyOwnerOtherContacts { get; set; }
        public virtual DbSet<WRBHBPropertyOwnerProperty> WRBHBPropertyOwnerProperties { get; set; }
        public virtual DbSet<WRBHBPropertyOwner> WRBHBPropertyOwners { get; set; }
        public virtual DbSet<WRBHBPropertyRoomBed> WRBHBPropertyRoomBeds { get; set; }
        public virtual DbSet<WRBHBPropertyRoomBedsHistory> WRBHBPropertyRoomBedsHistories { get; set; }
        public virtual DbSet<WRBHBPropertyRoom> WRBHBPropertyRooms { get; set; }
        public virtual DbSet<WRBHBPropertyRoomsHistory> WRBHBPropertyRoomsHistories { get; set; }
        public virtual DbSet<WRBHBPropertyType> WRBHBPropertyTypes { get; set; }
        public virtual DbSet<WRBHBPropertyUser> WRBHBPropertyUsers { get; set; }
        public virtual DbSet<WRBHBReconcilePayment> WRBHBReconcilePayments { get; set; }
        public virtual DbSet<WRBHBReconcilePaymentRef> WRBHBReconcilePaymentRefs { get; set; }
        public virtual DbSet<WRBHBRole> WRBHBRoles { get; set; }
        public virtual DbSet<WRBHBRolesGroup> WRBHBRolesGroups { get; set; }
        public virtual DbSet<WRBHBRolesRight> WRBHBRolesRights { get; set; }
        public virtual DbSet<WRBHBScreenMaster> WRBHBScreenMasters { get; set; }
        public virtual DbSet<WRBHBSSPCodeGeneration> WRBHBSSPCodeGenerations { get; set; }
        public virtual DbSet<WRBHBSSPCodeGenerationApartment> WRBHBSSPCodeGenerationApartments { get; set; }
        public virtual DbSet<WRBHBSSPCodeGenerationRoom> WRBHBSSPCodeGenerationRooms { get; set; }
        public virtual DbSet<WRBHBSSPCodeGenerationService> WRBHBSSPCodeGenerationServices { get; set; }
        public virtual DbSet<WRBHBState> WRBHBStates { get; set; }
        public virtual DbSet<WRBHBStaticHotel> WRBHBStaticHotels { get; set; }
        public virtual DbSet<WRBHBStaticHotels123> WRBHBStaticHotels123 { get; set; }
        public virtual DbSet<WRBHBTaxMapping> WRBHBTaxMappings { get; set; }
        public virtual DbSet<WRBHBTDSDeclaration> WRBHBTDSDeclarations { get; set; }
        public virtual DbSet<WRBHBTDSSlab> WRBHBTDSSlabs { get; set; }
        public virtual DbSet<WRBHBTiaAndNTia> WRBHBTiaAndNTias { get; set; }
        public virtual DbSet<WRBHBTransSubsPriceModel> WRBHBTransSubsPriceModels { get; set; }
        public virtual DbSet<WRBHBTripAdvicerData> WRBHBTripAdvicerDatas { get; set; }
        public virtual DbSet<WRBHBUser> WRBHBUsers { get; set; }
        public virtual DbSet<WRBHBUserGroup> WRBHBUserGroups { get; set; }
        public virtual DbSet<WRBHBUserRole> WRBHBUserRoles { get; set; }
        public virtual DbSet<WRBHBVendor> WRBHBVendors { get; set; }
        public virtual DbSet<WRBHBVendorAdvancePayment> WRBHBVendorAdvancePayments { get; set; }
        public virtual DbSet<WRBHBVendorCategory> WRBHBVendorCategories { get; set; }
        public virtual DbSet<WRBHBVendorChequeApprovalDtl> WRBHBVendorChequeApprovalDtls { get; set; }
        public virtual DbSet<WRBHBVendorChequeApprovalNewDtl> WRBHBVendorChequeApprovalNewDtls { get; set; }
        public virtual DbSet<WRBHBVendorCost> WRBHBVendorCosts { get; set; }
        public virtual DbSet<WRBHBVendorRequest> WRBHBVendorRequests { get; set; }
        public virtual DbSet<WRBHBVendorRequestDtl> WRBHBVendorRequestDtls { get; set; }
        public virtual DbSet<WRBHBVendorRequestTemp> WRBHBVendorRequestTemps { get; set; }
        public virtual DbSet<WRBHBVendorRequestTempDtl> WRBHBVendorRequestTempDtls { get; set; }
        public virtual DbSet<WRBHBVendorSettlementAdjusmentAdvanceAmount> WRBHBVendorSettlementAdjusmentAdvanceAmounts { get; set; }
        public virtual DbSet<WRBHBVendorSettlementHdr> WRBHBVendorSettlementHdrs { get; set; }
        public virtual DbSet<WRBHBVendorSettlementInvoiceAmount> WRBHBVendorSettlementInvoiceAmounts { get; set; }
        public virtual DbSet<WRBHBVendorSettlementPaidAmount> WRBHBVendorSettlementPaidAmounts { get; set; }
        public virtual DbSet<WRBHBVendorSettlementTACInvoiceAmount> WRBHBVendorSettlementTACInvoiceAmounts { get; set; }
        public virtual DbSet<WRBHBContractProductSubMaster> WRBHBContractProductSubMasters { get; set; }
        public virtual DbSet<WRBHBLaundrServiceDtl> WRBHBLaundrServiceDtls { get; set; }
        public virtual DbSet<WRBHBLaundrServiceHdr> WRBHBLaundrServiceHdrs { get; set; }
        public virtual DbSet<WRBHBNewKOTEntryDtl> WRBHBNewKOTEntryDtls { get; set; }
        public virtual DbSet<WRBHBNewKOTEntryHdr> WRBHBNewKOTEntryHdrs { get; set; }
        public virtual DbSet<WRBHBNewKOTUserEntryDtl> WRBHBNewKOTUserEntryDtls { get; set; }
        public virtual DbSet<WRBHBNewKOTUserEntryHdr> WRBHBNewKOTUserEntryHdrs { get; set; }
        public virtual DbSet<WRBHBNewPettyCashApprovalDtl> WRBHBNewPettyCashApprovalDtls { get; set; }
        public virtual DbSet<WRBHBNewPettyCashApprovalHdr> WRBHBNewPettyCashApprovalHdrs { get; set; }
        public virtual DbSet<WRBHBOutsourceKOTDtl> WRBHBOutsourceKOTDtls { get; set; }
        public virtual DbSet<WRBHBOutsourceKOTHdr> WRBHBOutsourceKOTHdrs { get; set; }
        public virtual DbSet<WRBHBPettyCashApprovalHdr> WRBHBPettyCashApprovalHdrs { get; set; }
        public virtual DbSet<WRBHBReference> WRBHBReferences { get; set; }
        public virtual DbSet<WRBHBTaxMaster> WRBHBTaxMasters { get; set; }
        public virtual DbSet<WRBHBVendorChequeApprovalHdr> WRBHBVendorChequeApprovalHdrs { get; set; }
        public virtual DbSet<WRBHBVendorChequeApprovalNewHdr> WRBHBVendorChequeApprovalNewHdrs { get; set; }
        public virtual DbSet<WRBHBVendorRequestType> WRBHBVendorRequestTypes { get; set; }
        public virtual DbSet<WrbhbTravelDesk> WrbhbTravelDesks { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    
        public virtual ObjectResult<DecryptPswd_Result> DecryptPswd(string userEmail)
        {
            var userEmailParameter = userEmail != null ?
                new ObjectParameter("UserEmail", userEmail) :
                new ObjectParameter("UserEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DecryptPswd_Result>("DecryptPswd", userEmailParameter);
        }
    
        public virtual ObjectResult<SP_Booking_FrontEnd_Help> SP_Booking_FrontEnd_Help(string action, string str1, string str2, string chkInDt, string chkOutDt, Nullable<long> stateId, Nullable<long> cityId, Nullable<long> clientId, Nullable<long> propertyId, Nullable<long> gradeId, Nullable<long> id1, Nullable<long> id2)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var str1Parameter = str1 != null ?
                new ObjectParameter("Str1", str1) :
                new ObjectParameter("Str1", typeof(string));
    
            var str2Parameter = str2 != null ?
                new ObjectParameter("Str2", str2) :
                new ObjectParameter("Str2", typeof(string));
    
            var chkInDtParameter = chkInDt != null ?
                new ObjectParameter("ChkInDt", chkInDt) :
                new ObjectParameter("ChkInDt", typeof(string));
    
            var chkOutDtParameter = chkOutDt != null ?
                new ObjectParameter("ChkOutDt", chkOutDt) :
                new ObjectParameter("ChkOutDt", typeof(string));
    
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("StateId", stateId) :
                new ObjectParameter("StateId", typeof(long));
    
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("CityId", cityId) :
                new ObjectParameter("CityId", typeof(long));
    
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(long));
    
            var propertyIdParameter = propertyId.HasValue ?
                new ObjectParameter("PropertyId", propertyId) :
                new ObjectParameter("PropertyId", typeof(long));
    
            var gradeIdParameter = gradeId.HasValue ?
                new ObjectParameter("GradeId", gradeId) :
                new ObjectParameter("GradeId", typeof(long));
    
            var id1Parameter = id1.HasValue ?
                new ObjectParameter("Id1", id1) :
                new ObjectParameter("Id1", typeof(long));
    
            var id2Parameter = id2.HasValue ?
                new ObjectParameter("Id2", id2) :
                new ObjectParameter("Id2", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Booking_FrontEnd_Help>("SP_Booking_FrontEnd_Help", actionParameter, str1Parameter, str2Parameter, chkInDtParameter, chkOutDtParameter, stateIdParameter, cityIdParameter, clientIdParameter, propertyIdParameter, gradeIdParameter, id1Parameter, id2Parameter);
        }
    }
}
