//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    
    public partial class SP_BookingPropertyDtls_Help_SA_FrontEnd
    {
        public string label { get; set; }
        public long Id { get; set; }
        public decimal Tariff { get; set; }
        public string GetType { get; set; }
        public string PropertyType { get; set; }
    }
}
