//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    
    public partial class SP_New_Booking_FrontEnd_Help_First
    {
        public long PropertyId { get; set; }
        public string PropertyName { get; set; }
        public decimal Tariff { get; set; }
        public string PropertyType { get; set; }
        public string PropertyDescription { get; set; }
        public string ImageLocation { get; set; }
        public string shortDescription { get; set; }
        public string StarRating { get; set; }
        public string Locality { get; set; }
        public long LocalityId { get; set; }
        public string LatitudeLongitude { get; set; }
    }
}
