//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    
    public partial class SP_New_Booking_FrontEnd_Help_Second
    {
        public string PropertyName { get; set; }
        public long PropertyId { get; set; }
        public string GetType { get; set; }
        public string PropertyType { get; set; }
        public string RoomType { get; set; }
        public decimal SingleTariff { get; set; }
        public decimal DoubleTariff { get; set; }
        public decimal TripleTariff { get; set; }
        public decimal SingleandMarkup { get; set; }
        public decimal DoubleandMarkup { get; set; }
        public decimal TripleandMarkup { get; set; }
        public bool TAC { get; set; }
        public string Inclusions { get; set; }
        public bool DiscountModeRS { get; set; }
        public bool DiscountModePer { get; set; }
        public decimal DiscountAllowed { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Locality { get; set; }
        public long LocalityId { get; set; }
        public long MarkupId { get; set; }
        public decimal SingleandMarkup1 { get; set; }
        public decimal DoubleandMarkup1 { get; set; }
        public decimal TripleandMarkup1 { get; set; }
        public string StarRating { get; set; }
        public string TaxAdded { get; set; }
        public string RatePlanCode { get; set; }
        public string RoomTypeCode { get; set; }
        public long APIHdrId { get; set; }
        public string MealPlan { get; set; }
        public string TripadvisorRating { get; set; }
        public decimal LTAgreed { get; set; }
        public decimal STAgreed { get; set; }
        public decimal LTRack { get; set; }
        public bool TaxInclusive { get; set; }
        public decimal BaseTariff { get; set; }
        public decimal GeneralMarkup { get; set; }
        public decimal SC { get; set; }
        public string LatitudeLongitude { get; set; }
        public string ImageLocation { get; set; }
        public string TaxSymbol { get; set; }
    }
}
