//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrbhbTravelDesk
    {
        public string ClientName { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string Mobile { get; set; }
        public string Office { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string States { get; set; }
        public int StateId { get; set; }
        public string City { get; set; }
        public int CityId { get; set; }
        public string Website { get; set; }
        public string Mode { get; set; }
        public string Addresss { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public decimal App_UserId { get; set; }
    }
}
