//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBTripAdvicerData
    {
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> MMTId { get; set; }
        public long Id { get; set; }
        public string SeeAllPhotos { get; set; }
        public string WebURL { get; set; }
        public string PercentRecommended { get; set; }
        public string LocationString { get; set; }
        public string LocationId { get; set; }
        public string WriteReview { get; set; }
        public string PriceLevel { get; set; }
        public string Distance { get; set; }
        public string NumReviews { get; set; }
        public string RatingImageURL { get; set; }
        public string HotalName { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string AddressString { get; set; }
        public string Categoryname { get; set; }
        public string CategoryLocalizedName { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryLocalizedName { get; set; }
        public string APIDetailURL { get; set; }
        public string AncestorsAbbrv { get; set; }
        public string AncestorsLevel { get; set; }
        public string AncestorsName { get; set; }
        public string AncestorsLocationId { get; set; }
        public string Bearing { get; set; }
        public string Longitude { get; set; }
        public string Rating { get; set; }
        public string Latitude { get; set; }
        public string RankingData { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public string Geo_location_id { get; set; }
        public string Geo_location_name { get; set; }
        public string Ranking_string { get; set; }
        public string Ranking_out_of { get; set; }
        public string Ranking { get; set; }
    }
}
