//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBTDSSlab
    {
        public decimal SlabFrom1 { get; set; }
        public decimal SlabTo1 { get; set; }
        public decimal SlabTax1 { get; set; }
        public decimal SlabFrom2 { get; set; }
        public decimal SlabTo2 { get; set; }
        public decimal SlabTax2 { get; set; }
        public decimal SlabFrom3 { get; set; }
        public decimal SlabTo3 { get; set; }
        public decimal SlabTax3 { get; set; }
        public decimal SlabFrom4 { get; set; }
        public decimal SlabTo4 { get; set; }
        public decimal SlabTax4 { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
    }
}
