//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBookingProperty
    {
        public long BookingId { get; set; }
        public string PropertyName { get; set; }
        public long PropertyId { get; set; }
        public string GetType { get; set; }
        public string PropertyType { get; set; }
        public string RoomType { get; set; }
        public decimal SingleTariff { get; set; }
        public Nullable<decimal> DoubleTariff { get; set; }
        public Nullable<decimal> TripleTariff { get; set; }
        public Nullable<decimal> SingleandMarkup { get; set; }
        public Nullable<decimal> DoubleandMarkup { get; set; }
        public Nullable<decimal> TripleandMarkup { get; set; }
        public decimal Markup { get; set; }
        public Nullable<bool> TAC { get; set; }
        public string Inclusions { get; set; }
        public Nullable<bool> DiscountModeRS { get; set; }
        public Nullable<bool> DiscountModePer { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Locality { get; set; }
        public long LocalityId { get; set; }
        public Nullable<long> MarkupId { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<decimal> SingleandMarkup1 { get; set; }
        public Nullable<decimal> DoubleandMarkup1 { get; set; }
        public Nullable<decimal> TripleandMarkup1 { get; set; }
        public Nullable<long> APIHdrId { get; set; }
        public string RatePlanCode { get; set; }
        public string RoomTypeCode { get; set; }
        public Nullable<decimal> SingleRoomRate { get; set; }
        public Nullable<decimal> SingleTaxes { get; set; }
        public Nullable<decimal> SingleRoomDiscount { get; set; }
        public Nullable<decimal> DubRoomRate { get; set; }
        public Nullable<decimal> DubTaxes { get; set; }
        public Nullable<decimal> DubRoomDiscount { get; set; }
        public Nullable<decimal> AmountAfterTax { get; set; }
        public Nullable<decimal> AmountBeforeTax { get; set; }
        public string AvaRatePlanCode { get; set; }
        public string AvailabilityResponseReferenceKey { get; set; }
        public string BookResponseReferenceKey { get; set; }
        public string BookHotelReservationIdvalue { get; set; }
        public string BookHotelReservationIdtype { get; set; }
        public Nullable<decimal> TACPer { get; set; }
        public string TaxAdded { get; set; }
        public Nullable<decimal> TotalCancelAmount { get; set; }
        public Nullable<decimal> CancellationMarkup { get; set; }
        public string Errorcode { get; set; }
        public string Description1 { get; set; }
        public Nullable<decimal> LTAgreed { get; set; }
        public Nullable<decimal> STAgreed { get; set; }
        public Nullable<decimal> LTRack { get; set; }
        public Nullable<bool> TaxInclusive { get; set; }
        public Nullable<decimal> BaseTariff { get; set; }
        public Nullable<decimal> GeneralMarkup { get; set; }
        public Nullable<bool> ExpWithTax { get; set; }
        public Nullable<decimal> SC { get; set; }
    }
}
