//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBFeedBckForm
    {
        public long Id { get; set; }
        public string GuestName { get; set; }
        public Nullable<long> GuestId { get; set; }
        public string ClientName { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string BookingCode { get; set; }
        public string PropertyName { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public string Remarks { get; set; }
        public string CheckOutDate { get; set; }
        public Nullable<long> CheckOutId { get; set; }
        public Nullable<long> ChkinId { get; set; }
        public string Cleanlinessofrooms { get; set; }
        public string QualityofFoodServed { get; set; }
        public string InternetService { get; set; }
        public string RoomAmbience { get; set; }
        public string QualityofService { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> Createdby { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> UnSubscribe { get; set; }
        public Nullable<bool> ChkinFlag { get; set; }
        public Nullable<bool> ChkOutFlag { get; set; }
        public Nullable<long> BookingId { get; set; }
        public string OverallStayExperience { get; set; }
        public string CheckInDate { get; set; }
        public string ChkRowId { get; set; }
    }
}
