//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPropertyOwnerApartment
    {
        public Nullable<long> OwnerId { get; set; }
        public Nullable<long> ApartmentId { get; set; }
        public string ApartmentName { get; set; }
        public int Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
    
        public virtual WRBHBPropertyApartment WRBHBPropertyApartment { get; set; }
        public virtual WRBHBPropertyOwner WRBHBPropertyOwner { get; set; }
    }
}
