//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBInvoiceManagedGHAmount
    {
        public Nullable<long> ManagedGHAmountMonthGenerated { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> RentelAmount { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public string Type { get; set; }
        public long Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public string Attention { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> LTTax { get; set; }
        public Nullable<decimal> STTax { get; set; }
        public Nullable<decimal> Cess { get; set; }
        public Nullable<decimal> HCess { get; set; }
        public Nullable<decimal> LTPer { get; set; }
        public Nullable<decimal> STper { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
