//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPropertyApartmentHistory
    {
        public Nullable<long> PropertyApartmentId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public string ApartmentName { get; set; }
        public string ApartmentType { get; set; }
        public string ApartmentNo { get; set; }
        public string SellableApartmentType { get; set; }
        public string OwnershipType { get; set; }
        public decimal RackTariff { get; set; }
        public bool DiscountModePer { get; set; }
        public bool DiscountModeRS { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public string Status { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
    }
}
