//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendorRequestDtl
    {
        public int VendorRequestHdrId { get; set; }
        public int ApartmentId { get; set; }
        public int Roomid { get; set; }
        public string Description { get; set; }
        public string Filepath { get; set; }
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Modifiedby { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public string BillNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
