//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBMapPOAndVendorPaymentDtl
    {
        public long Id { get; set; }
        public Nullable<long> MapPOAndVendorPaymentHdrId { get; set; }
        public Nullable<long> CheckOutId { get; set; }
        public Nullable<long> BookingId { get; set; }
        public string PONo { get; set; }
        public string BookingCode { get; set; }
        public string BillNumber { get; set; }
        public Nullable<decimal> POAmount { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string GuestName { get; set; }
        public string StayDuration { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
    }
}
