//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBClientManagement
    {
        public WRBHBClientManagement()
        {
            this.WRBHBClientGrades = new HashSet<WRBHBClientGrade>();
            this.WRBHBClientGradeValues = new HashSet<WRBHBClientGradeValue>();
        }
    
        public Nullable<long> MasterClientId { get; set; }
        public long SalesExecutiveId { get; set; }
        public long KeyAccountPersonId { get; set; }
        public long CRMId { get; set; }
        public string ClientName { get; set; }
        public string CAddress1 { get; set; }
        public string CAddress2 { get; set; }
        public string CCountry { get; set; }
        public string CState { get; set; }
        public string CCity { get; set; }
        public string CLocality { get; set; }
        public string CPincode { get; set; }
        public string ContactNo { get; set; }
        public bool DirectPay { get; set; }
        public Nullable<bool> BTC { get; set; }
        public decimal CreditLimit { get; set; }
        public string CreditPeriodNumber { get; set; }
        public string CreditPeriod { get; set; }
        public string Status { get; set; }
        public string BAddress1 { get; set; }
        public string BAddress2 { get; set; }
        public string BCountry { get; set; }
        public string BState { get; set; }
        public string BCity { get; set; }
        public string BLocality { get; set; }
        public string BPincode { get; set; }
        public string DomainName { get; set; }
        public string IndustryType { get; set; }
        public string CPhoneNo1 { get; set; }
        public string CPhoneNo2 { get; set; }
        public string CPhoneNo3 { get; set; }
        public string CPhoneNo4 { get; set; }
        public string CPhoneNo5 { get; set; }
        public string ClientLogo { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string InCCountry { get; set; }
        public string InBCountry { get; set; }
        public Nullable<bool> ServiceCharge { get; set; }
        public string ImageName { get; set; }
        public string TRClientURL { get; set; }
    
        public virtual ICollection<WRBHBClientGrade> WRBHBClientGrades { get; set; }
        public virtual ICollection<WRBHBClientGradeValue> WRBHBClientGradeValues { get; set; }
    }
}
