//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBTaxMaster
    {
        public long Id { get; set; }
        public decimal Cess { get; set; }
        public decimal HECess { get; set; }
        public decimal VAT { get; set; }
        public decimal ServiceTaxOnTariff { get; set; }
        public decimal TariffAmtFrom { get; set; }
        public decimal TariffAmtTo { get; set; }
        public decimal LTaxper { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string State { get; set; }
        public long StateId { get; set; }
        public System.DateTime Date { get; set; }
        public string VATNo { get; set; }
        public string LuxuryNo { get; set; }
        public Nullable<decimal> TariffAmtFrom1 { get; set; }
        public Nullable<decimal> TariffAmtTo1 { get; set; }
        public Nullable<decimal> LTaxper1 { get; set; }
        public Nullable<decimal> TariffAmtFrom2 { get; set; }
        public Nullable<decimal> TariffAmtTo2 { get; set; }
        public Nullable<decimal> LTaxper2 { get; set; }
        public Nullable<decimal> TariffAmtFrom3 { get; set; }
        public Nullable<decimal> TariffAmtTo3 { get; set; }
        public Nullable<decimal> LTaxper3 { get; set; }
        public string ServiceNo { get; set; }
        public Nullable<decimal> RestaurantST { get; set; }
        public Nullable<decimal> BusinessSupportST { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> RackTariff { get; set; }
        public string TINNumber { get; set; }
        public string CINNumber { get; set; }
    }
}
