//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBRolesRight
    {
        public int Id { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> scrId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> RolesId { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<System.Guid> rowid { get; set; }
    
        public virtual WRBHBRole WRBHBRole { get; set; }
    }
}
