//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBProperty
    {
        public string PropertyName { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public string PropertDescription { get; set; }
        public string Prefix { get; set; }
        public string Propertaddress { get; set; }
        public string City { get; set; }
        public string Localityarea { get; set; }
        public string State { get; set; }
        public string Postal { get; set; }
        public string Phone { get; set; }
        public string Directions { get; set; }
        public string Keyword { get; set; }
        public Nullable<bool> ServicesSwimPool { get; set; }
        public Nullable<bool> ServicesPub { get; set; }
        public Nullable<bool> ServicesGym { get; set; }
        public Nullable<bool> ServicesRestaurant { get; set; }
        public Nullable<bool> ServicesConfHall { get; set; }
        public Nullable<bool> ServicesCyberCafe { get; set; }
        public Nullable<bool> ServicesLaundry { get; set; }
        public Nullable<bool> ShowOnWebsite { get; set; }
        public string LatitudeLongitude { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public long Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocalityId { get; set; }
        public string TotalNoRooms { get; set; }
        public Nullable<decimal> RackTarrifSingle { get; set; }
        public Nullable<long> PropertyType { get; set; }
        public Nullable<decimal> RackTarrifDouble { get; set; }
        public string BookingPolicy { get; set; }
        public string CancelPolicy { get; set; }
        public string Email { get; set; }
        public Nullable<long> TypeId { get; set; }
        public string CheckOutType { get; set; }
        public Nullable<int> CheckIn { get; set; }
        public string CheckInType { get; set; }
        public Nullable<int> CheckOut { get; set; }
        public Nullable<int> GraceTime { get; set; }
        public Nullable<decimal> TRIPRating { get; set; }
    }
}
