//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendorRequest
    {
        public int PropertyId { get; set; }
        public string Property { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string Service { get; set; }
        public string Type { get; set; }
        public int ApartmentId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string BillNo { get; set; }
        public string Duedate { get; set; }
        public string VendorBill { get; set; }
        public string Description { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public string Status { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool Flag { get; set; }
        public Nullable<int> Partial { get; set; }
        public Nullable<int> ApprovalId { get; set; }
    }
}
