//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendorAdvancePayment
    {
        public long Id { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public string PropertyName { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<System.DateTime> DateofPayment { get; set; }
        public string Comments { get; set; }
        public string BankName { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<bool> SettlementFlag { get; set; }
    }
}
