//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBSSPCodeGeneration
    {
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public string SSPName { get; set; }
        public string SSPCode { get; set; }
        public string BookingLevel { get; set; }
        public Nullable<decimal> SingleTariff { get; set; }
        public Nullable<decimal> DoubleTariff { get; set; }
        public long Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<decimal> TripleTariff { get; set; }
    }
}
