//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBCompanyMaster
    {
        public string LegalCompanyName { get; set; }
        public string CompanyShortName { get; set; }
        public string Address { get; set; }
        public long City { get; set; }
        public int State { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PanCardNo { get; set; }
        public string Logo { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public string ImageName { get; set; }
    }
}
