//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBooking
    {
        public long BookingCode { get; set; }
        public Nullable<long> TrackingNo { get; set; }
        public long ClientId { get; set; }
        public long GradeId { get; set; }
        public long StateId { get; set; }
        public long CityId { get; set; }
        public string ClientName { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public string ExpectedChkInTime { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string GradeName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string ClientBookerId { get; set; }
        public string ClientBookerName { get; set; }
        public string ClientBookerEmail { get; set; }
        public bool EmailtoGuest { get; set; }
        public string Note { get; set; }
        public string SpecialRequirements { get; set; }
        public string Status { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string Sales { get; set; }
        public string CRM { get; set; }
        public string CancelRemarks { get; set; }
        public string AMPM { get; set; }
        public string BookingLevel { get; set; }
        public string PONo { get; set; }
        public long PONoId { get; set; }
        public string CancelStatus { get; set; }
        public Nullable<System.DateTime> BookedDt { get; set; }
        public Nullable<long> BookedUsrId { get; set; }
        public Nullable<bool> FrontEnd { get; set; }
        public string MMTPONo { get; set; }
        public Nullable<long> MMTPONoId { get; set; }
        public string ExtraCCEmail { get; set; }
        public Nullable<bool> HRPolicy { get; set; }
        public string HRPolicyOverrideRemarks { get; set; }
        public string PropertyRefNo { get; set; }
        public Nullable<bool> PaymentFlag { get; set; }
        public Nullable<long> PaymentCode { get; set; }
        public string PaymentCodeRemarks { get; set; }
    }
}
