//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBankTransaction
    {
        public string AccountNumber { get; set; }
        public string TransactionDate { get; set; }
        public string ValueDate { get; set; }
        public string Description { get; set; }
        public string RefNo { get; set; }
        public string BranchCode { get; set; }
        public decimal Credit { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
    }
}
