//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBTCSubmissionDetail
    {
        public long BTCSubmissionId { get; set; }
        public long DepositDetilsId { get; set; }
        public long ClientId { get; set; }
        public long ChkOutHdrId { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceType { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CollectionStatus { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
    }
}
