//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBMasterClientManagement
    {
        public Nullable<int> MasterClientId { get; set; }
        public string ClientName { get; set; }
        public string CAddress1 { get; set; }
        public string CAddress2 { get; set; }
        public string CCountry { get; set; }
        public string CState { get; set; }
        public string CCity { get; set; }
        public string CLocality { get; set; }
        public string CPincode { get; set; }
        public string ContactNo { get; set; }
        public string DomainName { get; set; }
        public string CPhoneNo1 { get; set; }
        public string CPhoneNo2 { get; set; }
        public string CPhoneNo3 { get; set; }
        public string CPhoneNo4 { get; set; }
        public string CPhoneNo5 { get; set; }
        public string ClientLogo { get; set; }
        public string InCCountry { get; set; }
        public long Id { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
    }
}
