//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBChechkOutHdr
    {
        public Nullable<long> ChkInHdrId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public string CheckOutNo { get; set; }
        public string GuestName { get; set; }
        public string Stay { get; set; }
        public string Type { get; set; }
        public string BookingLevel { get; set; }
        public string BillDate { get; set; }
        public string ClientName { get; set; }
        public string Property { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public decimal ChkOutTariffTotal { get; set; }
        public decimal ChkOutTariffAdays { get; set; }
        public decimal ChkOutTariffDiscount { get; set; }
        public decimal ChkOutTariffLT { get; set; }
        public decimal ChkOutTariffST1 { get; set; }
        public decimal ChkOutTariffST2 { get; set; }
        public decimal ChkOutTariffSC { get; set; }
        public decimal ChkOutTariffST3 { get; set; }
        public decimal ChkOutTariffCess { get; set; }
        public decimal ChkOutTariffHECess { get; set; }
        public decimal ChkOutTariffNetAmount { get; set; }
        public string ChkOutTariffReferance { get; set; }
        public string Name { get; set; }
        public string ChkOutTariffExtraType { get; set; }
        public Nullable<int> ChkOutTariffExtraDays { get; set; }
        public Nullable<decimal> ChkOutTariffExtraAmount { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public string CheckInType { get; set; }
        public Nullable<int> BedId { get; set; }
        public string BedNo { get; set; }
        public string ApartmentNo { get; set; }
        public Nullable<int> ApartmentId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Direct { get; set; }
        public string BTC { get; set; }
        public string PropertyType { get; set; }
        public Nullable<decimal> STAgreedAmount { get; set; }
        public Nullable<decimal> LTAgreedAmount { get; set; }
        public Nullable<decimal> STRackAmount { get; set; }
        public Nullable<decimal> LTRackAmount { get; set; }
        public string Status { get; set; }
        public string CheckOutDate { get; set; }
        public string CheckInDate { get; set; }
        public Nullable<bool> PrintInvoice { get; set; }
        public string InVoiceNo { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> Flag { get; set; }
        public string ServiceTaxPer { get; set; }
        public string LuxuryTaxPer { get; set; }
        public Nullable<bool> ServiceEntryFlag { get; set; }
        public Nullable<decimal> VATPer { get; set; }
        public Nullable<decimal> RestaurantSTPer { get; set; }
        public Nullable<decimal> BusinessSupportST { get; set; }
        public string BillFromDate { get; set; }
        public string BillEndDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ServiceChargeChk { get; set; }
        public Nullable<int> IntermediateFlag { get; set; }
        public string Intermediate { get; set; }
        public string PIInvoice { get; set; }
        public string CollectVendor { get; set; }
        public Nullable<bool> Preformainvoice { get; set; }
        public string Email { get; set; }
        public string TariffPaymentMode { get; set; }
        public string BookingType { get; set; }
    }
}
