//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBContractManagementTariffAppartment
    {
        public long ContractId { get; set; }
        public string Place { get; set; }
        public string Property { get; set; }
        public System.DateTime Attachedon { get; set; }
        public string AttachedBy { get; set; }
        public System.DateTime Detachedon { get; set; }
        public bool Detach { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> ApartmentId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<decimal> Tariff { get; set; }
        public Nullable<long> BlockId { get; set; }
    
        public virtual WRBHBContractManagement WRBHBContractManagement { get; set; }
    }
}
