//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBRole
    {
        public WRBHBRole()
        {
            this.WRBHBRolesRights = new HashSet<WRBHBRolesRight>();
            this.WRBHBUserRoles = new HashSet<WRBHBUserRole>();
        }
    
        public Nullable<int> RoleGroupId { get; set; }
        public string RoleName { get; set; }
        public string RoleGroup { get; set; }
        public string Statuss { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
    
        public virtual WRBHBRolesGroup WRBHBRolesGroup { get; set; }
        public virtual ICollection<WRBHBRolesRight> WRBHBRolesRights { get; set; }
        public virtual ICollection<WRBHBUserRole> WRBHBUserRoles { get; set; }
    }
}
