//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPCExpenseApproval
    {
        public string RequestedOn { get; set; }
        public string Requestedby { get; set; }
        public string PCAccount { get; set; }
        public decimal ApprovedAmount { get; set; }
        public decimal ExpenseAmount { get; set; }
        public string ProcessedStatus { get; set; }
        public string LastProcessedon { get; set; }
        public string Comments { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RequestedUserId { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<bool> Process { get; set; }
        public Nullable<int> PropertyId { get; set; }
    }
}
