//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendorSettlementTACInvoiceAmount
    {
        public Nullable<long> VendorSettlementHdId { get; set; }
        public Nullable<long> TACId { get; set; }
        public string TACInvoiceNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> TACAmount { get; set; }
        public Nullable<decimal> TotalBusinessSupportST { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> AdjusementAmount { get; set; }
        public Nullable<decimal> Adjusment { get; set; }
        public long Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
    }
}
