//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBKOTDtl
    {
        public long KOTEntryHdrId { get; set; }
        public long PropertyId { get; set; }
        public long BookingId { get; set; }
        public string BookingCode { get; set; }
        public string GuestName { get; set; }
        public string RoomNo { get; set; }
        public Nullable<long> BreakfastVeg { get; set; }
        public Nullable<long> BreakfastNonVeg { get; set; }
        public Nullable<long> LunchVeg { get; set; }
        public Nullable<long> LunchNonVeg { get; set; }
        public Nullable<long> DinnerVeg { get; set; }
        public Nullable<long> DinnerNonVeg { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<int> CheckInId { get; set; }
        public Nullable<System.DateTime> HdrDate { get; set; }
        public Nullable<bool> CheckOutServiceFlag { get; set; }
    }
}
