//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBChechkOutPaymentCard
    {
        public Nullable<long> ChkOutHdrId { get; set; }
        public string Payment { get; set; }
        public string PayeeName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string PaymentMode { get; set; }
        public string CardDetails { get; set; }
        public string CCBrand { get; set; }
        public string NameoftheCard { get; set; }
        public string CreditCardNo { get; set; }
        public string ExpiryOn { get; set; }
        public string ROC { get; set; }
        public string SOCBatchCloseNo { get; set; }
        public string AmountSwipedFor { get; set; }
        public long Id { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<int> ExpiryMonth { get; set; }
        public Nullable<int> ExpiryYear { get; set; }
        public Nullable<decimal> OutStanding { get; set; }
    }
}
