//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBExternalChechkOutTAC
    {
        public Nullable<long> ChkInHdrId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> BookingId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> GuestId { get; set; }
        public string TACInvoiceNo { get; set; }
        public string TACInvoiceFile { get; set; }
        public string GuestName { get; set; }
        public string BillDate { get; set; }
        public string ClientName { get; set; }
        public string Property { get; set; }
        public string PropertyType { get; set; }
        public string Status { get; set; }
        public string Direct { get; set; }
        public string CheckInDate { get; set; }
        public string CheckOutDate { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> ChkOutTariffTotal { get; set; }
        public Nullable<decimal> ChkOutTariffCess { get; set; }
        public Nullable<decimal> ChkOutTariffHECess { get; set; }
        public Nullable<decimal> ChkOutTariffNetAmount { get; set; }
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<decimal> MarkUpAmount { get; set; }
        public Nullable<decimal> BusinessSupportST { get; set; }
        public Nullable<int> ChkOutHdrId { get; set; }
        public Nullable<decimal> TotalBusinessSupportST { get; set; }
        public Nullable<decimal> TACAmount { get; set; }
        public Nullable<int> Flag { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<bool> SettlementFlag { get; set; }
        public Nullable<int> IntermediateFlag { get; set; }
        public string Intermediate { get; set; }
        public string BillFromDate { get; set; }
        public string BillEndDate { get; set; }
    }
}
