 SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[dbo].[HBMenu_PropertyWisePaymentType_Report]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
	DROP PROCEDURE [dbo].[HBMenu_PropertyWisePaymentType_Report]
GO 
CREATE PROCEDURE [dbo].[HBMenu_PropertyWisePaymentType_Report](@Action NVARCHAR(100),@Str NVARCHAR(100),
@FromDt NVARCHAR(100),@ToDt NVARCHAR(100),@ClientId BIGINT)
AS
BEGIN
SET NOCOUNT ON
SET ANSI_WARNINGS OFF

IF @Action = 'PageLoad1'
 BEGIN
  SELECT ClientName,Id FROM WRBHBClientManagement WHERE IsActive=1 AND IsDeleted=0
  ORDER BY ClientName ASC 
 END
  
  
IF @Action = 'PageLoad'
 BEGIN
  
  
  CREATE TABLE #TMP(BookingId BIGINT,BookingLevel NVARCHAR(100),
  BookingCode BIGINT,ChkInDt DATE,ChkOutDt DATE,
  Tariff DECIMAL(27,2),TariffPaymentMode NVARCHAR(100),
  RoomCaptured INT,RoomId BIGINT,RoomShiftingFlag INT);
  -- ROOM BEGIN
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,PG.RoomCaptured,PG.RoomId,PG.RoomShiftingFlag 
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBookingProperty BP WITH(NOLOCK)ON 
  BP.BookingId=B.Id
  LEFT OUTER JOIN WRBHBBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id AND PG.BookingPropertyTableId=BP.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Room' AND B.ClientId=@ClientId AND
  BP.IsActive=1 AND BP.IsDeleted=0 AND PG.Tariff != 0 AND
  BP.PropertyType IN ('ExP','InP','CPP') AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103);
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME);*/
  
  
  -- 
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,PG.RoomCaptured,PG.RoomId,PG.RoomShiftingFlag
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBookingProperty BP WITH(NOLOCK)ON 
  BP.BookingId=B.Id
  LEFT OUTER JOIN WRBHBBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id AND PG.BookingPropertyTableId=BP.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Room' AND B.ClientId=@ClientId AND
  BP.IsActive=1 AND BP.IsDeleted=0 AND PG.Tariff != 0 AND
  BP.PropertyType IN ('ExP','InP','CPP') AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103);
  /*CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME);*/
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,PG.RoomCaptured,PG.RoomId,PG.RoomShiftingFlag
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBookingProperty BP WITH(NOLOCK)ON 
  BP.BookingId=B.Id
  LEFT OUTER JOIN WRBHBBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id AND PG.BookingPropertyTableId=BP.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Room' AND B.ClientId=@ClientId AND
  BP.IsActive=1 AND BP.IsDeleted=0 AND PG.Tariff != 0 AND
  BP.PropertyType IN ('ExP','InP','CPP') AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103) AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103);
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME);*/
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,PG.RoomCaptured,PG.RoomId,PG.RoomShiftingFlag
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBookingProperty BP WITH(NOLOCK)ON 
  BP.BookingId=B.Id
  LEFT OUTER JOIN WRBHBBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id AND PG.BookingPropertyTableId=BP.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Room' AND B.ClientId=@ClientId AND
  BP.IsActive=1 AND BP.IsDeleted=0 AND PG.Tariff != 0 AND
  BP.PropertyType IN ('ExP','InP','CPP') AND
  PG.ChkInDt <= CONVERT(date,@FromDt,103) AND PG.ChkOutDt >= CONVERT(date,@FromDt,103);
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) <= 
  CAST(@FromDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) >=
  CAST(@FromDt AS DATETIME);*/
  --
  
  -- ROOM END
  -- BED BEGIN
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.BedId,0 
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBedBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Bed' AND B.ClientId=@ClientId AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  -- 
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.BedId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBedBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Bed' AND B.ClientId=@ClientId AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.BedId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBedBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Bed' AND B.ClientId=@ClientId AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.BedId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBedBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Bed' AND B.ClientId=@ClientId AND
  PG.ChkInDt <= CONVERT(date,@FromDt,103) AND PG.ChkOutDt >= CONVERT(date,@FromDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) <= 
  CAST(@FromDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) >=
  CAST(@FromDt AS DATETIME)*/ AND PG.Tariff != 0;
  -- BED END
  -- APARTMENT BEGIN
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.ApartmentId,0 
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBApartmentBookingPropertyAssingedGuest PG WITH(NOLOCK)ON
  PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Apartment' AND B.ClientId=@ClientId AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  -- 
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.ApartmentId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBApartmentBookingPropertyAssingedGuest PG 
  WITH(NOLOCK)ON PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Apartment' AND B.ClientId=@ClientId AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.ApartmentId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBApartmentBookingPropertyAssingedGuest PG 
  WITH(NOLOCK)ON PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Apartment' AND B.ClientId=@ClientId AND
  PG.ChkInDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103) AND
  PG.ChkOutDt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) BETWEEN 
  CAST(@FromDt AS DATETIME) AND CAST(@ToDt AS DATETIME)*/ AND PG.Tariff != 0;
  --
  INSERT INTO #TMP(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,RoomShiftingFlag)
  SELECT B.Id,B.BookingLevel,B.BookingCode,PG.ChkInDt,PG.ChkOutDt,
  PG.Tariff,PG.TariffPaymentMode,1,PG.ApartmentId,0
  FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBApartmentBookingPropertyAssingedGuest PG 
  WITH(NOLOCK)ON PG.BookingId=B.Id
  WHERE B.IsActive=1 AND B.IsDeleted=0 AND PG.IsActive=1 AND 
  PG.IsDeleted=0 AND B.BookingLevel='Apartment' AND B.ClientId=@ClientId AND
  PG.ChkInDt <= CONVERT(date,@FromDt,103) AND PG.ChkOutDt >= CONVERT(date,@FromDt,103)
  --CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  /*CAST(CAST(PG.ChkInDt AS VARCHAR)+' '+
  CAST(PG.ExpectChkInTime+' '+PG.AMPM AS VARCHAR) AS DATETIME) <= 
  CAST(@FromDt AS DATETIME) AND
  CAST(CAST(PG.ChkOutDt AS VARCHAR)+' '+'11:59:00 AM' AS DATETIME) >=
  CAST(@FromDt AS DATETIME)*/ AND PG.Tariff != 0;
  -- APARTMENT END
  CREATE TABLE #TMP1(BookingId BIGINT,BookingLevel NVARCHAR(100),
  BookingCode BIGINT,ChkInDt DATE,ChkOutDt DATE,
  Tariff DECIMAL(27,2),TariffPaymentMode NVARCHAR(100),
  RoomCaptured INT,RoomId BIGINT,NoofStay INT);
  INSERT INTO #TMP1(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay)
  SELECT BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,
  DATEDIFF(DAY,ChkInDt,ChkOutDt) FROM #TMP
  GROUP BY BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId;
  --
  --select * from #TMP1;RETURN;
  --GROUP BY BookingId,BookingLevel order by BookingId,BookingLevel;return;
  --
  CREATE TABLE #NoofStay1(BookingId BIGINT,BookingLevel NVARCHAR(100),
  Dt DATE,Tariff DECIMAL(27,2),
  TariffPaymentMode NVARCHAR(100),RoomCaptured INT,RoomId BIGINT,
  NoofStay INT);
  INSERT INTO #NoofStay1(BookingId,BookingLevel,Dt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay)
  SELECT BookingId,BookingLevel,ChkInDt,Tariff,TariffPaymentMode,
  RoomCaptured,RoomId,NoofStay FROM #TMP1 WHERE NoofStay=1;
  --
  CREATE TABLE #TMPNoofStay(BookingId BIGINT,BookingLevel NVARCHAR(100),
  BookingCode BIGINT,ChkInDt DATE,ChkOutDt DATE,
  Tariff DECIMAL(27,2),TariffPaymentMode NVARCHAR(100),
  RoomCaptured INT,RoomId BIGINT,NoofStay INT,
  Id BIGINT IDENTITY(1,1));
  INSERT INTO #TMPNoofStay(BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay)
  SELECT BookingId,BookingLevel,BookingCode,ChkInDt,ChkOutDt,
  Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay 
  FROM #TMP1 WHERE NoofStay > 1;
  --
  --SELECT * FROM #NoofStay1;
  --SELECT * FROM #TMPNoofStay;RETURN;
  DECLARE @Cnt INT,@Id BIGINT,@NoofStay INT,@InCnt INT,@DtAdd DATE;
  SET @Cnt=(SELECT COUNT(*) FROM #TMPNoofStay);
  WHILE @Cnt > 0
   BEGIN
    SET @Id = (SELECT TOP 1 Id FROM #TMPNoofStay ORDER BY Id ASC);
    SET @NoofStay = (SELECT NoofStay FROM #TMPNoofStay WHERE Id=@Id);
    SET @DtAdd = (SELECT ChkInDt FROM #TMPNoofStay WHERE Id=@Id);
    SET @InCnt = 0;    
    WHILE @InCnt < @NoofStay
     BEGIN
      INSERT INTO #NoofStay1(BookingId,BookingLevel,Dt,
      Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay)
      SELECT BookingId,BookingLevel,DATEADD(DAY,@InCnt,@DtAdd),
      Tariff,TariffPaymentMode,RoomCaptured,RoomId,NoofStay
      FROM #TMPNoofStay WHERE Id=@Id;
      SET @InCnt += 1;
     END
    DELETE FROM #TMPNoofStay WHERE Id=@Id;
    SET @Cnt=(SELECT COUNT(*) FROM #TMPNoofStay);
   END
  --
  --SELECT * FROM #NoofStay1 ORDER BY BookingId;RETURN;
  --
  DECLARE @MonthCnt INT,@F DATE,@T NVARCHAR(100);
  DECLARE @AddCnt INT;
  SET @MonthCnt = (SELECT DATEDIFF(MONTH,CONVERT(date,@FromDt,103),CONVERT(date,@ToDt,103)));
  SET @AddCnt = 0;
  SET @F = CONVERT(date,@ToDt,103);
  CREATE TABLE #MONTH(Dt DATE);
  IF @MonthCnt = 0
   BEGIN
    INSERT INTO #MONTH(Dt)VALUES(@F);
   END
  ELSE
   BEGIN
    SET @MonthCnt += 1;
    WHILE @MonthCnt > @AddCnt
     BEGIN
      INSERT INTO #MONTH(Dt)VALUES(@F)
      SET @F = DATEADD(MONTH,1,@F);
      SET @AddCnt += 1;
      IF MONTH(@F) = MONTH(CONVERT(date,@ToDt,103)) AND YEAR(@F) = YEAR(CONVERT(date,@ToDt,103))
       BEGIN
        SET @F = CONVERT(date,@ToDt,103);
       END
     END
   END
  --
  --SELECT * FROM #MONTH;
  --SELECT SUM(Tariff) FROM #NoofStay1;return;
  --SELECT * FROM #NoofStay1 ORDER BY BookingId;RETURN;
  --
  CREATE TABLE #TNS(BookingId BIGINT,BookingLevel NVARCHAR(100),
  Tariff DECIMAL(27,2),TariffPaymentMode NVARCHAR(100),Dt DATE,
  RoomCaptured INT,NoofStay INT,RoomId BIGINT);
  INSERT INTO #TNS(BookingId,BookingLevel,Tariff,TariffPaymentMode,Dt,
  RoomCaptured,NoofStay,RoomId)
  SELECT N.BookingId,N.BookingLevel,N.Tariff,N.TariffPaymentMode,N.Dt,
  N.RoomCaptured,N.NoofStay,N.RoomId FROM #NoofStay1 N
  WHERE N.Dt BETWEEN CONVERT(date,@FromDt,103) AND CONVERT(date,@ToDt,103)
  GROUP BY N.BookingId,N.BookingLevel,N.TariffPaymentMode,N.Dt,
  N.RoomCaptured,N.NoofStay,N.Tariff,N.RoomId;
  --
  --SELECT * FROM #TNS ORDER BY BookingId;RETURN;
  --
  DECLARE @Mnt INT = (SELECT COUNT(*) FROM #MONTH);
  CREATE TABLE #TABLE(BookingId BIGINT,BookingLevel NVARCHAR(100),
  Tariff DECIMAL(27,2),TariffPaymentMode NVARCHAR(100),Mnth INT,Yr INT);
  IF @Mnt = 1
   BEGIN
    INSERT INTO #TABLE(BookingId,BookingLevel,Tariff,TariffPaymentMode,Mnth,Yr)
    SELECT N.BookingId,N.BookingLevel,SUM(N.Tariff),
    N.TariffPaymentMode,MONTH(@FromDt),YEAR(@FromDt) FROM #TNS N
    GROUP BY N.BookingId,N.BookingLevel,N.TariffPaymentMode;
   END
  ELSE
   BEGIN
    CREATE TABLE #TMPMONTH(Dt DATE,Id INT IDENTITY(1,1));
    INSERT INTO #TMPMONTH(Dt)
    SELECT Dt FROM #MONTH;
    DECLARE @MntCnt INT = (SELECT COUNT(*) FROM #TMPMONTH);
    DECLARE @MntId INT,@Month DATE;    
    WHILE @Mnt > 0
     BEGIN
      SELECT TOP 1 @MntId=Id,@Month=Dt FROM #TMPMONTH;
      INSERT INTO #TABLE(BookingId,BookingLevel,Tariff,TariffPaymentMode,
      Mnth,Yr)
      SELECT N.BookingId,N.BookingLevel,SUM(N.Tariff),
      N.TariffPaymentMode,MONTH(@Month),YEAR(@Month) FROM #NoofStay1 N
      WHERE MONTH(N.Dt) = MONTH(@Month) AND YEAR(N.Dt) = YEAR(@Month)
      GROUP BY N.BookingId,N.BookingLevel,N.TariffPaymentMode;
      DELETE FROM #TMPMONTH WHERE Id=@MntId;      
      SET @Mnt=(SELECT COUNT(*) FROM #TMPMONTH);
     END
   END
  --
  --SELECT * FROM #TABLE;return;
  --
  CREATE TABLE #TABLE1(BookingPropertyId BIGINT,BookingId BIGINT,
  CityId BIGINT,ClientId BIGINT);
  -- Apartment
  INSERT INTO #TABLE1(BookingId,BookingPropertyId,CityId,ClientId)
  SELECT B.Id,B1.BookingPropertyId,B.CityId,B.ClientId FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBApartmentBookingPropertyAssingedGuest B1
  WITH(NOLOCK)ON B1.BookingId=B.Id
  WHERE B.Id IN (SELECT BookingId FROM #TABLE 
  WHERE BookingLevel='Apartment')
  GROUP BY B.Id,B1.BookingPropertyId,B.CityId,B.ClientId;
  -- Bed
  INSERT INTO #TABLE1(BookingId,BookingPropertyId,CityId,ClientId)
  SELECT B.Id,B1.BookingPropertyId,B.CityId,B.ClientId FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBedBookingPropertyAssingedGuest B1
  WITH(NOLOCK)ON B1.BookingId=B.Id
  WHERE B.Id IN (SELECT BookingId FROM #TABLE 
  WHERE BookingLevel='Bed') 
  GROUP BY B.Id,B1.BookingPropertyId,B.CityId,B.ClientId;
  -- Room
  INSERT INTO #TABLE1(BookingId,BookingPropertyId,CityId,ClientId)
  SELECT B.Id,B1.BookingPropertyId,B.CityId,B.ClientId FROM WRBHBBooking B
  LEFT OUTER JOIN WRBHBBookingPropertyAssingedGuest B1
  WITH(NOLOCK)ON B1.BookingId=B.Id
  WHERE B.Id IN (SELECT BookingId FROM #TABLE 
  WHERE BookingLevel='Room') 
  GROUP BY B.Id,B1.BookingPropertyId,B.CityId,B.ClientId;
  --
  --SELECT * FROM #TABLE1;RETURN;
  --
  CREATE TABLE #CITYPROPERTY(CityName NVARCHAR(100),CityId BIGINT,
  PropertyName NVARCHAR(100),PropertyId BIGINT);
  INSERT INTO #CITYPROPERTY(CityName,CityId,PropertyName,PropertyId)
  SELECT C.CityName,T.CityId,P.PropertyName,T.BookingPropertyId FROM #TABLE1 T
  LEFT OUTER JOIN WRBHBProperty P WITH(NOLOCK)ON P.Id=T.BookingPropertyId
  LEFT OUTER JOIN WRBHBCity C WITH(NOLOCK)ON C.Id=T.CityId
  GROUP BY T.CityId,C.CityName,T.BookingPropertyId,P.PropertyName;
  -- Payment Type Wise Split Data
  CREATE TABLE #ASD(BTC DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),
  DIRECT DECIMAL(27,2),Mnth INT,Yr INT,PropertyId BIGINT,
  CityId BIGINT);
  --
  --SELECT * FROM #TABLE;RETURN;
  -- Bill to Company (BTC)
  INSERT INTO #ASD(BTC,BILLTOCLIENT,DIRECT,Mnth,Yr,PropertyId,CityId)
  SELECT SUM(T.Tariff),0,0,T.Mnth,T.Yr,T1.BookingPropertyId,T1.CityId 
  FROM #TABLE T
  LEFT OUTER JOIN #TABLE1 T1 WITH(NOLOCK)ON T1.BookingId=T.BookingId
  WHERE T.TariffPaymentMode='Bill to Company (BTC)'
  GROUP BY T.Mnth,T.Yr,T1.BookingPropertyId,T1.CityId;
  -- Direct
  INSERT INTO #ASD(BTC,BILLTOCLIENT,DIRECT,Mnth,Yr,PropertyId,CityId)
  SELECT 0,0,SUM(T.Tariff),T.Mnth,T.Yr,T1.BookingPropertyId,T1.CityId 
  FROM #TABLE T
  LEFT OUTER JOIN #TABLE1 T1 WITH(NOLOCK)ON T1.BookingId=T.BookingId
  WHERE T.TariffPaymentMode='Direct'
  GROUP BY T.Mnth,T.Yr,T1.BookingPropertyId,T1.CityId; 
  -- Bill to Client
  INSERT INTO #ASD(BTC,BILLTOCLIENT,DIRECT,Mnth,Yr,PropertyId,CityId)
  SELECT 0,SUM(T.Tariff),0,T.Mnth,T.Yr,
  T1.BookingPropertyId,T1.CityId FROM #TABLE T
  LEFT OUTER JOIN #TABLE1 T1 WITH(NOLOCK)ON T1.BookingId=T.BookingId
  WHERE T.TariffPaymentMode='Bill to Client'
  GROUP BY T.Mnth,T.Yr,T1.BookingPropertyId,T1.CityId;  
  --
  --SELECT CP.CityName,CP.PropertyName,cp.CityId,cp.PropertyId FROM #CITYPROPERTY CP;
  --SELECT * FROM #ASD;RETURN;
  --
  CREATE TABLE #Month1(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month2(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month3(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month4(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month5(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month6(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month7(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month8(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month9(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month10(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month11(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  CREATE TABLE #Month12(CityId BIGINT,PropertyId BIGINT,BTC DECIMAL(27,2),
  DIRECT DECIMAL(27,2),BILLTOCLIENT DECIMAL(27,2),Mnth INT,Yr INT);
  --  
  CREATE TABLE #QAZ(Dt DATE,Id INT IDENTITY(1,1));
  INSERT INTO #QAZ(Dt)SELECT Dt FROM #MONTH;
  --SELECT * FROM #QAZ;
  DECLARE @QAZId INT = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  -- Month 1  
  INSERT INTO #Month1(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY CP.CityId,CP.PropertyId,A.Mnth,A.Yr;
  -- Month 2
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month2(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 3
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month3(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 4
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month4(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 5
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month5(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 6
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month6(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 7
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month7(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 8
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month8(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 9
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month9(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 10
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month10(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 11
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month11(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  -- Month 12
  DELETE FROM #QAZ WHERE Id=@QAZId;
  SET @QAZId = (SELECT TOP 1 Id FROM #QAZ ORDER BY Id ASC);
  INSERT INTO #Month12(CityId,PropertyId,BTC,DIRECT,BILLTOCLIENT,Mnth,Yr)
  SELECT CP.CityId,CP.PropertyId,SUM(ISNULL(A.BTC,0)),
  SUM(ISNULL(A.DIRECT,0)),SUM(ISNULL(A.BILLTOCLIENT,0)),
  A.Mnth,A.Yr FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #ASD A WITH(NOLOCK)ON CP.CityId = A.CityId AND 
  CP.PropertyId=A.PropertyId AND 
  A.Mnth=(SELECT MONTH(Dt) FROM #QAZ WHERE Id=@QAZId) AND
  A.Yr=(SELECT YEAR(Dt) FROM #QAZ WHERE Id=@QAZId)
  GROUP BY A.Mnth,A.Yr,CP.CityId,CP.PropertyId;
  --
  --SELECT * FROM #Month1;RETURN;
  --SELECT * FROM #Month2 ORDER BY CityId ASC;return;
  --
  CREATE TABLE #FINAL(CityId BIGINT,CityName NVARCHAR(100),PropertyId BIGINT,
  PropertyName NVARCHAR(100),M1BTC NVARCHAR(100),M1DIRECT NVARCHAR(100),
  M1BILLTOCLIENT NVARCHAR(100),M1Tot NVARCHAR(100),M2BTC NVARCHAR(100),
  M2DIRECT NVARCHAR(100),M2BILLTOCLIENT NVARCHAR(100),M2Tot NVARCHAR(100),
  M3BTC NVARCHAR(100),M3DIRECT NVARCHAR(100),M3BILLTOCLIENT NVARCHAR(100),
  M3Tot NVARCHAR(100),M4BTC NVARCHAR(100),M4DIRECT NVARCHAR(100),
  M4BILLTOCLIENT NVARCHAR(100),M4Tot NVARCHAR(100),M5BTC NVARCHAR(100),
  M5DIRECT NVARCHAR(100),M5BILLTOCLIENT NVARCHAR(100),M5Tot NVARCHAR(100),
  M6BTC NVARCHAR(100),M6DIRECT NVARCHAR(100),M6BILLTOCLIENT NVARCHAR(100),
  M6Tot NVARCHAR(100),M7BTC NVARCHAR(100),M7DIRECT NVARCHAR(100),
  M7BILLTOCLIENT NVARCHAR(100),M7Tot NVARCHAR(100),M8BTC NVARCHAR(100),
  M8DIRECT NVARCHAR(100),M8BILLTOCLIENT NVARCHAR(100),M8Tot NVARCHAR(100),
  M9BTC NVARCHAR(100),M9DIRECT NVARCHAR(100),M9BILLTOCLIENT NVARCHAR(100),
  M9Tot NVARCHAR(100),M10BTC NVARCHAR(100),M10DIRECT NVARCHAR(100),
  M10BILLTOCLIENT NVARCHAR(100),M10Tot NVARCHAR(100),M11BTC NVARCHAR(100),
  M11DIRECT NVARCHAR(100),M11BILLTOCLIENT NVARCHAR(100),M11Tot NVARCHAR(100),
  M12BTC NVARCHAR(100),M12DIRECT NVARCHAR(100),M12BILLTOCLIENT NVARCHAR(100),
  M12Tot NVARCHAR(100),GrandTotal NVARCHAR(100));
  INSERT INTO #FINAL(CityId,CityName,PropertyId,PropertyName,
  M1BTC,M1DIRECT,M1BILLTOCLIENT,
  M1Tot,M2BTC,M2DIRECT,M2BILLTOCLIENT,M2Tot,M3BTC,M3DIRECT,M3BILLTOCLIENT,M3Tot,
  M4BTC,M4DIRECT,M4BILLTOCLIENT,M4Tot,M5BTC,M5DIRECT,M5BILLTOCLIENT,M5Tot,M6BTC,
  M6DIRECT,M6BILLTOCLIENT,M6Tot,M7BTC,M7DIRECT,M7BILLTOCLIENT,M7Tot,M8BTC,
  M8DIRECT,M8BILLTOCLIENT,M8Tot,M9BTC,M9DIRECT,M9BILLTOCLIENT,M9Tot,M10BTC,
  M10DIRECT,M10BILLTOCLIENT,M10Tot,M11BTC,M11DIRECT,M11BILLTOCLIENT,M11Tot,
  M12BTC,M12DIRECT,M12BILLTOCLIENT,M12Tot,GrandTotal)
  SELECT CP.CityId,CP.CityName,CP.PropertyId,CP.PropertyName,  
  M1.BTC,M1.DIRECT,M1.BILLTOCLIENT,(M1.BTC+M1.DIRECT+M1.BILLTOCLIENT) AS 
  Month1Tot,  
  M2.BTC,M2.DIRECT,M2.BILLTOCLIENT,(M2.BTC+M2.DIRECT+M2.BILLTOCLIENT) AS 
  Month2Tot,
  M3.BTC,M3.DIRECT,M3.BILLTOCLIENT,(M3.BTC+M3.DIRECT+M3.BILLTOCLIENT) AS 
  Month3Tot,
  M4.BTC,M4.DIRECT,M4.BILLTOCLIENT,(M4.BTC+M4.DIRECT+M4.BILLTOCLIENT) AS 
  Month4Tot,
  M5.BTC,M5.DIRECT,M5.BILLTOCLIENT,(M5.BTC+M5.DIRECT+M5.BILLTOCLIENT) AS 
  Month5Tot,
  M6.BTC,M6.DIRECT,M6.BILLTOCLIENT,(M6.BTC+M6.DIRECT+M6.BILLTOCLIENT) AS 
  Month6Tot,
  M7.BTC,M7.DIRECT,M7.BILLTOCLIENT,(M7.BTC+M7.DIRECT+M7.BILLTOCLIENT) AS 
  Month7Tot,
  M8.BTC,M8.DIRECT,M8.BILLTOCLIENT,(M8.BTC+M8.DIRECT+M8.BILLTOCLIENT) AS 
  Month8Tot,
  M9.BTC,M9.DIRECT,M9.BILLTOCLIENT,(M9.BTC+M9.DIRECT+M9.BILLTOCLIENT) AS 
  Month9Tot,
  M10.BTC,M10.DIRECT,M10.BILLTOCLIENT,(M10.BTC+M10.DIRECT+M10.BILLTOCLIENT) AS 
  Month10Tot,
  M11.BTC,M11.DIRECT,M11.BILLTOCLIENT,(M11.BTC+M11.DIRECT+M11.BILLTOCLIENT) AS 
  Month11Tot,
  M12.BTC,M12.DIRECT,M12.BILLTOCLIENT,(M12.BTC+M12.DIRECT+M12.BILLTOCLIENT) AS 
  Month12Tot,(M1.BTC+M1.DIRECT+M1.BILLTOCLIENT+M2.BTC+M2.DIRECT+M2.BILLTOCLIENT+
  M3.BTC+M3.DIRECT+M3.BILLTOCLIENT+M4.BTC+M4.DIRECT+M4.BILLTOCLIENT+M5.BTC+
  M5.DIRECT+M5.BILLTOCLIENT+M6.BTC+M6.DIRECT+M6.BILLTOCLIENT+M7.BTC+M7.DIRECT+
  M7.BILLTOCLIENT+M8.BTC+M8.DIRECT+M8.BILLTOCLIENT+M9.BTC+M9.DIRECT+
  M9.BILLTOCLIENT+M10.BTC+M10.DIRECT+M10.BILLTOCLIENT+M11.BTC+M11.DIRECT+
  M11.BILLTOCLIENT+M12.BTC+M12.DIRECT+M12.BILLTOCLIENT)
  FROM #CITYPROPERTY CP
  LEFT OUTER JOIN #Month1 M1 WITH(NOLOCK)ON CP.CityId=M1.CityId AND
  CP.PropertyId=M1.PropertyId
  LEFT OUTER JOIN #Month2 M2 WITH(NOLOCK)ON CP.CityId=M2.CityId AND
  CP.PropertyId=M2.PropertyId
  LEFT OUTER JOIN #Month3 M3 WITH(NOLOCK)ON CP.CityId=M3.CityId AND
  CP.PropertyId=M3.PropertyId
  LEFT OUTER JOIN #Month4 M4 WITH(NOLOCK)ON CP.CityId=M4.CityId AND
  CP.PropertyId=M4.PropertyId
  LEFT OUTER JOIN #Month5 M5 WITH(NOLOCK)ON CP.CityId=M5.CityId AND
  CP.PropertyId=M5.PropertyId
  LEFT OUTER JOIN #Month6 M6 WITH(NOLOCK)ON CP.CityId=M6.CityId AND
  CP.PropertyId=M6.PropertyId
  LEFT OUTER JOIN #Month7 M7 WITH(NOLOCK)ON CP.CityId=M7.CityId AND
  CP.PropertyId=M7.PropertyId
  LEFT OUTER JOIN #Month8 M8 WITH(NOLOCK)ON CP.CityId=M8.CityId AND
  CP.PropertyId=M8.PropertyId
  LEFT OUTER JOIN #Month9 M9 WITH(NOLOCK)ON CP.CityId=M9.CityId AND
  CP.PropertyId=M9.PropertyId
  LEFT OUTER JOIN #Month10 M10 WITH(NOLOCK)ON CP.CityId=M10.CityId AND
  CP.PropertyId=M10.PropertyId
  LEFT OUTER JOIN #Month11 M11 WITH(NOLOCK)ON CP.CityId=M11.CityId AND
  CP.PropertyId=M11.PropertyId
  LEFT OUTER JOIN #Month12 M12 WITH(NOLOCK)ON CP.CityId=M12.CityId AND
  CP.PropertyId=M12.PropertyId;
  --
  /*INSERT INTO #FINAL(CityId,CityName,PropertyId,PropertyName,
  M1BTC,M1DIRECT,M1BILLTOCLIENT,
  M1Tot,M2BTC,M2DIRECT,M2BILLTOCLIENT,M2Tot,M3BTC,M3DIRECT,M3BILLTOCLIENT,M3Tot,
  M4BTC,M4DIRECT,M4BILLTOCLIENT,M4Tot,M5BTC,M5DIRECT,M5BILLTOCLIENT,M5Tot,M6BTC,
  M6DIRECT,M6BILLTOCLIENT,M6Tot,M7BTC,M7DIRECT,M7BILLTOCLIENT,M7Tot,M8BTC,
  M8DIRECT,M8BILLTOCLIENT,M8Tot,M9BTC,M9DIRECT,M9BILLTOCLIENT,M9Tot,M10BTC,
  M10DIRECT,M10BILLTOCLIENT,M10Tot,M11BTC,M11DIRECT,M11BILLTOCLIENT,M11Tot,
  M12BTC,M12DIRECT,M12BILLTOCLIENT,M12Tot,GrandTotal)
  SELECT 0,'ZZZ',0,'Grand Total',SUM(M1BTC),SUM(M1DIRECT),SUM(M1BILLTOCLIENT),
  SUM(M1Tot),SUM(M2BTC),SUM(M2DIRECT),SUM(M2BILLTOCLIENT),SUM(M2Tot),
  SUM(M3BTC),SUM(M3DIRECT),SUM(M3BILLTOCLIENT),SUM(M3Tot),SUM(M4BTC),
  SUM(M4DIRECT),SUM(M4BILLTOCLIENT),SUM(M4Tot),SUM(M5BTC),SUM(M5DIRECT),
  SUM(M5BILLTOCLIENT),SUM(M5Tot),SUM(M6BTC),SUM(M6DIRECT),SUM(M6BILLTOCLIENT),
  SUM(M6Tot),SUM(M7BTC),SUM(M7DIRECT),SUM(M7BILLTOCLIENT),SUM(M7Tot),SUM(M8BTC),
  SUM(M8DIRECT),SUM(M8BILLTOCLIENT),SUM(M8Tot),SUM(M9BTC),SUM(M9DIRECT),
  SUM(M9BILLTOCLIENT),SUM(M9Tot),SUM(M10BTC),SUM(M10DIRECT),
  SUM(M10BILLTOCLIENT),SUM(M10Tot),SUM(M11BTC),SUM(M11DIRECT),
  SUM(M11BILLTOCLIENT),SUM(M11Tot),SUM(M12BTC),SUM(M12DIRECT),
  SUM(M12BILLTOCLIENT),SUM(M12Tot),SUM(GrandTotal) 
  FROM #FINAL;
  --
  CREATE TABLE #FINAL1(CityId BIGINT,CityName NVARCHAR(100),
  PropertyId BIGINT,PropertyName NVARCHAR(100),
  M1BTC NVARCHAR(100),M1DIRECT NVARCHAR(100),M1BILLTOCLIENT NVARCHAR(100),
  M1Tot NVARCHAR(100),M2BTC NVARCHAR(100),M2DIRECT NVARCHAR(100),
  M2BILLTOCLIENT NVARCHAR(100),M2Tot NVARCHAR(100),M3BTC NVARCHAR(100),
  M3DIRECT NVARCHAR(100),M3BILLTOCLIENT NVARCHAR(100),M3Tot NVARCHAR(100),
  M4BTC NVARCHAR(100),M4DIRECT NVARCHAR(100),M4BILLTOCLIENT NVARCHAR(100),
  M4Tot NVARCHAR(100),M5BTC NVARCHAR(100),M5DIRECT NVARCHAR(100),
  M5BILLTOCLIENT NVARCHAR(100),M5Tot NVARCHAR(100),M6BTC NVARCHAR(100),
  M6DIRECT NVARCHAR(100),M6BILLTOCLIENT NVARCHAR(100),M6Tot NVARCHAR(100),
  M7BTC NVARCHAR(100),M7DIRECT NVARCHAR(100),M7BILLTOCLIENT NVARCHAR(100),
  M7Tot NVARCHAR(100),M8BTC NVARCHAR(100),M8DIRECT NVARCHAR(100),
  M8BILLTOCLIENT NVARCHAR(100),M8Tot NVARCHAR(100),M9BTC NVARCHAR(100),
  M9DIRECT NVARCHAR(100),M9BILLTOCLIENT NVARCHAR(100),M9Tot NVARCHAR(100),
  M10BTC NVARCHAR(100),M10DIRECT NVARCHAR(100),M10BILLTOCLIENT NVARCHAR(100),
  M10Tot NVARCHAR(100),M11BTC NVARCHAR(100),M11DIRECT NVARCHAR(100),
  M11BILLTOCLIENT NVARCHAR(100),M11Tot NVARCHAR(100),
  M12BTC NVARCHAR(100),M12DIRECT NVARCHAR(100),
  M12BILLTOCLIENT NVARCHAR(100),M12Tot NVARCHAR(100),GrandTotal NVARCHAR(100));
  INSERT INTO #FINAL1(CityId,CityName,PropertyId,PropertyName,
  M1BTC,M1DIRECT,M1BILLTOCLIENT,
  M1Tot,M2BTC,M2DIRECT,M2BILLTOCLIENT,M2Tot,M3BTC,M3DIRECT,M3BILLTOCLIENT,M3Tot,
  M4BTC,M4DIRECT,M4BILLTOCLIENT,M4Tot,M5BTC,M5DIRECT,M5BILLTOCLIENT,M5Tot,M6BTC,
  M6DIRECT,M6BILLTOCLIENT,M6Tot,M7BTC,M7DIRECT,M7BILLTOCLIENT,M7Tot,M8BTC,
  M8DIRECT,M8BILLTOCLIENT,M8Tot,M9BTC,M9DIRECT,M9BILLTOCLIENT,M9Tot,M10BTC,
  M10DIRECT,M10BILLTOCLIENT,M10Tot,M11BTC,M11DIRECT,M11BILLTOCLIENT,M11Tot,
  M12BTC,M12DIRECT,M12BILLTOCLIENT,M12Tot,GrandTotal)
  SELECT CityId,CityName,PropertyId,PropertyName,
  M1BTC,M1DIRECT,M1BILLTOCLIENT,M1Tot,M2BTC,M2DIRECT,M2BILLTOCLIENT,M2Tot,
  M3BTC,M3DIRECT,M3BILLTOCLIENT,M3Tot,M4BTC,M4DIRECT,M4BILLTOCLIENT,M4Tot,
  M5BTC,M5DIRECT,M5BILLTOCLIENT,M5Tot,M6BTC,M6DIRECT,M6BILLTOCLIENT,M6Tot,
  M7BTC,M7DIRECT,M7BILLTOCLIENT,M7Tot,M8BTC,M8DIRECT,M8BILLTOCLIENT,M8Tot,
  M9BTC,M9DIRECT,M9BILLTOCLIENT,M9Tot,M10BTC,M10DIRECT,M10BILLTOCLIENT,
  M10Tot,M11BTC,M11DIRECT,M11BILLTOCLIENT,M11Tot,M12BTC,M12DIRECT,
  M12BILLTOCLIENT,M12Tot,GrandTotal FROM #FINAL;*/
  --
  --SELECT * FROM #FINAL1;RETURN;
  --
  DECLARE @FinalCnt INT = (SELECT COUNT(*) FROM #MONTH);
  /*DECLARE @AZXCnt DECIMAL(27,2) = (SELECT TOP 1 GrandTotal FROM #FINAL
  WHERE PropertyName='Grand Total' AND CityName='ZZZ' AND
  GrandTotal != '0.00');
  IF @AZXCnt > 0
  BEGIN*/
  IF @FinalCnt = 1
   BEGIN
    SELECT CityName,PropertyName,
    --CityId,PropertyId,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,
    CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;
   END
  IF @FinalCnt = 2
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL
    ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 3
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 4
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 5
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 6
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 7
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 8
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN M8BTC != '0.00' THEN M8BTC ELSE '' END AS M8BTC,
    CASE WHEN M8DIRECT != '0.00' THEN M8DIRECT ELSE '' END AS M8DIRECT,
    CASE WHEN M8BILLTOCLIENT != '0.00' THEN M8BILLTOCLIENT ELSE '' END AS 
    M8BILLTOCLIENT,CASE WHEN M8Tot != '0.00' THEN M8Tot ELSE '' END AS M8Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 9
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN M8BTC != '0.00' THEN M8BTC ELSE '' END AS M8BTC,
    CASE WHEN M8DIRECT != '0.00' THEN M8DIRECT ELSE '' END AS M8DIRECT,
    CASE WHEN M8BILLTOCLIENT != '0.00' THEN M8BILLTOCLIENT ELSE '' END AS 
    M8BILLTOCLIENT,CASE WHEN M8Tot != '0.00' THEN M8Tot ELSE '' END AS M8Tot,
    CASE WHEN M9BTC != '0.00' THEN M9BTC ELSE '' END AS M9BTC,
    CASE WHEN M9DIRECT != '0.00' THEN M9DIRECT ELSE '' END AS M9DIRECT,
    CASE WHEN M9BILLTOCLIENT != '0.00' THEN M9BILLTOCLIENT ELSE '' END AS 
    M9BILLTOCLIENT,CASE WHEN M9Tot != '0.00' THEN M9Tot ELSE '' END AS M9Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 10
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN M8BTC != '0.00' THEN M8BTC ELSE '' END AS M8BTC,
    CASE WHEN M8DIRECT != '0.00' THEN M8DIRECT ELSE '' END AS M8DIRECT,
    CASE WHEN M8BILLTOCLIENT != '0.00' THEN M8BILLTOCLIENT ELSE '' END AS 
    M8BILLTOCLIENT,CASE WHEN M8Tot != '0.00' THEN M8Tot ELSE '' END AS M8Tot,
    CASE WHEN M9BTC != '0.00' THEN M9BTC ELSE '' END AS M9BTC,
    CASE WHEN M9DIRECT != '0.00' THEN M9DIRECT ELSE '' END AS M9DIRECT,
    CASE WHEN M9BILLTOCLIENT != '0.00' THEN M9BILLTOCLIENT ELSE '' END AS 
    M9BILLTOCLIENT,CASE WHEN M9Tot != '0.00' THEN M9Tot ELSE '' END AS M9Tot,
    CASE WHEN M10BTC != '0.00' THEN M10BTC ELSE '' END AS M10BTC,
    CASE WHEN M10DIRECT != '0.00' THEN M10DIRECT ELSE '' END AS M10DIRECT,
    CASE WHEN M10BILLTOCLIENT != '0.00' THEN M10BILLTOCLIENT ELSE '' END AS 
    M10BILLTOCLIENT,CASE WHEN M10Tot != '0.00' THEN M10Tot ELSE '' END AS 
    M10Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt = 11
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN M8BTC != '0.00' THEN M8BTC ELSE '' END AS M8BTC,
    CASE WHEN M8DIRECT != '0.00' THEN M8DIRECT ELSE '' END AS M8DIRECT,
    CASE WHEN M8BILLTOCLIENT != '0.00' THEN M8BILLTOCLIENT ELSE '' END AS 
    M8BILLTOCLIENT,CASE WHEN M8Tot != '0.00' THEN M8Tot ELSE '' END AS M8Tot,
    CASE WHEN M9BTC != '0.00' THEN M9BTC ELSE '' END AS M9BTC,
    CASE WHEN M9DIRECT != '0.00' THEN M9DIRECT ELSE '' END AS M9DIRECT,
    CASE WHEN M9BILLTOCLIENT != '0.00' THEN M9BILLTOCLIENT ELSE '' END AS 
    M9BILLTOCLIENT,CASE WHEN M9Tot != '0.00' THEN M9Tot ELSE '' END AS M9Tot,
    CASE WHEN M10BTC != '0.00' THEN M10BTC ELSE '' END AS M10BTC,
    CASE WHEN M10DIRECT != '0.00' THEN M10DIRECT ELSE '' END AS M10DIRECT,
    CASE WHEN M10BILLTOCLIENT != '0.00' THEN M10BILLTOCLIENT ELSE '' END AS 
    M10BILLTOCLIENT,CASE WHEN M10Tot != '0.00' THEN M10Tot ELSE '' END AS 
    M10Tot,
    CASE WHEN M11BTC != '0.00' THEN M11BTC ELSE '' END AS M11BTC,
    CASE WHEN M11DIRECT != '0.00' THEN M11DIRECT ELSE '' END AS M11DIRECT,
    CASE WHEN M11BILLTOCLIENT != '0.00' THEN M11BILLTOCLIENT ELSE '' END AS 
    M11BILLTOCLIENT,CASE WHEN M11Tot != '0.00' THEN M11Tot ELSE '' END AS 
    M11Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
  IF @FinalCnt >= 12
   BEGIN
    SELECT CityName,PropertyName,
    CASE WHEN M1BTC != '0.00' THEN M1BTC ELSE '' END AS M1BTC,
    CASE WHEN M1DIRECT != '0.00' THEN M1DIRECT ELSE '' END AS M1DIRECT,
    CASE WHEN M1BILLTOCLIENT != '0.00' THEN M1BILLTOCLIENT ELSE '' END AS 
    M1BILLTOCLIENT,CASE WHEN M1Tot != '0.00' THEN M1Tot ELSE '' END AS M1Tot,
    CASE WHEN M2BTC != '0.00' THEN M2BTC ELSE '' END AS M2BTC,
    CASE WHEN M2DIRECT != '0.00' THEN M2DIRECT ELSE '' END AS M2DIRECT,
    CASE WHEN M2BILLTOCLIENT != '0.00' THEN M2BILLTOCLIENT ELSE '' END AS 
    M2BILLTOCLIENT,CASE WHEN M2Tot != '0.00' THEN M2Tot ELSE '' END AS M2Tot,
    CASE WHEN M3BTC != '0.00' THEN M3BTC ELSE '' END AS M3BTC,
    CASE WHEN M3DIRECT != '0.00' THEN M3DIRECT ELSE '' END AS M3DIRECT,
    CASE WHEN M3BILLTOCLIENT != '0.00' THEN M3BILLTOCLIENT ELSE '' END AS 
    M3BILLTOCLIENT,CASE WHEN M3Tot != '0.00' THEN M3Tot ELSE '' END AS M3Tot,
    CASE WHEN M4BTC != '0.00' THEN M4BTC ELSE '' END AS M4BTC,
    CASE WHEN M4DIRECT != '0.00' THEN M4DIRECT ELSE '' END AS M4DIRECT,
    CASE WHEN M4BILLTOCLIENT != '0.00' THEN M4BILLTOCLIENT ELSE '' END AS 
    M4BILLTOCLIENT,CASE WHEN M4Tot != '0.00' THEN M4Tot ELSE '' END AS M4Tot,
    CASE WHEN M5BTC != '0.00' THEN M5BTC ELSE '' END AS M5BTC,
    CASE WHEN M5DIRECT != '0.00' THEN M5DIRECT ELSE '' END AS M5DIRECT,
    CASE WHEN M5BILLTOCLIENT != '0.00' THEN M5BILLTOCLIENT ELSE '' END AS 
    M5BILLTOCLIENT,CASE WHEN M5Tot != '0.00' THEN M5Tot ELSE '' END AS M5Tot,
    CASE WHEN M6BTC != '0.00' THEN M6BTC ELSE '' END AS M6BTC,
    CASE WHEN M6DIRECT != '0.00' THEN M6DIRECT ELSE '' END AS M6DIRECT,
    CASE WHEN M6BILLTOCLIENT != '0.00' THEN M6BILLTOCLIENT ELSE '' END AS 
    M6BILLTOCLIENT,CASE WHEN M6Tot != '0.00' THEN M6Tot ELSE '' END AS M6Tot,
    CASE WHEN M7BTC != '0.00' THEN M7BTC ELSE '' END AS M7BTC,
    CASE WHEN M7DIRECT != '0.00' THEN M7DIRECT ELSE '' END AS M7DIRECT,
    CASE WHEN M7BILLTOCLIENT != '0.00' THEN M7BILLTOCLIENT ELSE '' END AS 
    M7BILLTOCLIENT,CASE WHEN M7Tot != '0.00' THEN M7Tot ELSE '' END AS M7Tot,
    CASE WHEN M8BTC != '0.00' THEN M8BTC ELSE '' END AS M8BTC,
    CASE WHEN M8DIRECT != '0.00' THEN M8DIRECT ELSE '' END AS M8DIRECT,
    CASE WHEN M8BILLTOCLIENT != '0.00' THEN M8BILLTOCLIENT ELSE '' END AS 
    M8BILLTOCLIENT,CASE WHEN M8Tot != '0.00' THEN M8Tot ELSE '' END AS M8Tot,
    CASE WHEN M9BTC != '0.00' THEN M9BTC ELSE '' END AS M9BTC,
    CASE WHEN M9DIRECT != '0.00' THEN M9DIRECT ELSE '' END AS M9DIRECT,
    CASE WHEN M9BILLTOCLIENT != '0.00' THEN M9BILLTOCLIENT ELSE '' END AS 
    M9BILLTOCLIENT,CASE WHEN M9Tot != '0.00' THEN M9Tot ELSE '' END AS M9Tot,
    CASE WHEN M10BTC != '0.00' THEN M10BTC ELSE '' END AS M10BTC,
    CASE WHEN M10DIRECT != '0.00' THEN M10DIRECT ELSE '' END AS M10DIRECT,
    CASE WHEN M10BILLTOCLIENT != '0.00' THEN M10BILLTOCLIENT ELSE '' END AS 
    M10BILLTOCLIENT,CASE WHEN M10Tot != '0.00' THEN M10Tot ELSE '' END AS 
    M10Tot,
    CASE WHEN M11BTC != '0.00' THEN M11BTC ELSE '' END AS M11BTC,
    CASE WHEN M11DIRECT != '0.00' THEN M11DIRECT ELSE '' END AS M11DIRECT,
    CASE WHEN M11BILLTOCLIENT != '0.00' THEN M11BILLTOCLIENT ELSE '' END AS 
    M11BILLTOCLIENT,CASE WHEN M11Tot != '0.00' THEN M11Tot ELSE '' END AS 
    M11Tot,
    CASE WHEN M12BTC != '0.00' THEN M12BTC ELSE '' END AS M12BTC,
    CASE WHEN M12DIRECT != '0.00' THEN M12DIRECT ELSE '' END AS M12DIRECT,
    CASE WHEN M12BILLTOCLIENT != '0.00' THEN M12BILLTOCLIENT ELSE '' END AS 
    M12BILLTOCLIENT,CASE WHEN M12Tot != '0.00' THEN M12Tot ELSE '' END AS 
    M12Tot,
    CASE WHEN GrandTotal != '0.00' THEN GrandTotal ELSE '' END AS GrandTotal
    FROM #FINAL ORDER BY CityName,PropertyName ASC;    
   END
 END
END  
--EXEC [dbo].[SP_PropertyWisePaymentType_Report] @Action='PageLoad',
--@FromDt='2014-08-01',@ToDt='2014-08-31',
--@ClientId=1528;

 /*select b.Id,p.PropertyType,p.GetType,g.ChkInDt,g.ExpectChkInTime,g.AMPM,
 g.ChkOutDt,g.Tariff,G.BookingPropertyId,G.RoomCaptured 
 from WRBHBBooking b
 left outer join WRBHBBookingProperty p on p.BookingId=b.Id
 left outer join WRBHBBookingPropertyAssingedGuest g on 
 g.BookingId=b.Id and g.BookingPropertyTableId=p.Id
 where g.IsActive=1 and g.IsDeleted=0 and
 B.Id in (2558,2509,2436);*/
