//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrRequest
    {
        public long ClientId { get; set; }
        public Nullable<long> ClientMgntRowId { get; set; }
        public string ClientName { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public string EmpMobile { get; set; }
        public string Designation { get; set; }
        public string Grade { get; set; }
        public string BusinessUnit { get; set; }
        public string Dept { get; set; }
        public string CostCenter { get; set; }
        public string Location { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorEmail { get; set; }
        public string TravelCity { get; set; }
        public string LocationCity { get; set; }
        public string Budget { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public string CheckInTime { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string CheckOutTime { get; set; }
        public string PaymentMode { get; set; }
        public string Purpose { get; set; }
        public string Request { get; set; }
        public string PickUp { get; set; }
        public long Id { get; set; }
        public string RowId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
