//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBNewKOTEntryHdr
    {
        public string PropertyName { get; set; }
        public long PropertyId { get; set; }
        public string GuestName { get; set; }
        public string Date { get; set; }
        public int GuestId { get; set; }
        public string GetType { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string RoomNo { get; set; }
        public string BookingCode { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> CheckInId { get; set; }
        public Nullable<bool> ChkoutServiceFlag { get; set; }
    }
}
