//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBContractClientPref_Details
    {
        public long HeaderId { get; set; }
        public string PropertyName { get; set; }
        public long PropertyId { get; set; }
        public string RoomType { get; set; }
        public long RoomId { get; set; }
        public Nullable<decimal> TariffSingle { get; set; }
        public Nullable<decimal> TariffDouble { get; set; }
        public Nullable<bool> TaxInclusive { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<decimal> TariffTriple { get; set; }
        public string Facility { get; set; }
        public string Email { get; set; }
        public string ContactPhone { get; set; }
        public string ContactName { get; set; }
        public Nullable<decimal> RTariffSingle { get; set; }
        public Nullable<decimal> RTariffDouble { get; set; }
        public Nullable<decimal> RTariffTriple { get; set; }
        public Nullable<decimal> LTAgreed { get; set; }
        public Nullable<decimal> LTRack { get; set; }
        public Nullable<decimal> STAgreed { get; set; }
    }
}
