//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBStaticHotel
    {
        public Nullable<int> HotelCount { get; set; }
        public string CityCode { get; set; }
        public string City { get; set; }
        public string StarRating { get; set; }
        public string HotalName { get; set; }
        public string HotalId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Area { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string Pincode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CheckOutTime { get; set; }
        public string CheckInTime { get; set; }
        public string TwentyFourHourCheckinAllowed { get; set; }
        public string ContactPerson { get; set; }
        public string Description { get; set; }
        public string WebAddress { get; set; }
        public string Image { get; set; }
        public string DateUpdated { get; set; }
        public string Mobile { get; set; }
        public string AlternateName { get; set; }
        public string Contact { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Fax { get; set; }
        public string Facility { get; set; }
        public string Currency { get; set; }
        public string Overallrating { get; set; }
        public string Recommended { get; set; }
        public string TotalRating { get; set; }
        public string TotalReviews { get; set; }
        public string Amenity { get; set; }
        public string Code { get; set; }
        public string RoomDescription { get; set; }
        public string RoomName { get; set; }
        public long Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<decimal> TRIPRating { get; set; }
        public string InActiveRemarks { get; set; }
    }
}
