//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBCheckOutServiceHdr
    {
        public long CheckOutHdrId { get; set; }
        public decimal ChkOutServiceAmtl { get; set; }
        public decimal ChkOutServiceVat { get; set; }
        public decimal ChkOutServiceLT { get; set; }
        public decimal ChkOutServiceST { get; set; }
        public decimal Cess { get; set; }
        public decimal HECess { get; set; }
        public decimal ChkOutServiceNetAmount { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> MiscellaneousAmount { get; set; }
        public string MiscellaneousRemarks { get; set; }
        public Nullable<decimal> OtherService { get; set; }
    }
}
