//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPropertyOwner
    {
        public WRBHBPropertyOwner()
        {
            this.WRBHBPropertyAgreementsOwners = new HashSet<WRBHBPropertyAgreementsOwner>();
            this.WRBHBPropertyOwnerApartments = new HashSet<WRBHBPropertyOwnerApartment>();
            this.WRBHBPropertyOwnerProperties = new HashSet<WRBHBPropertyOwnerProperty>();
        }
    
        public Nullable<long> PropertyId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string LedgerName { get; set; }
        public string EmailID { get; set; }
        public string Phone { get; set; }
        public string Alternatephone { get; set; }
        public Nullable<int> TDSPer { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string LocalityArea { get; set; }
        public string State { get; set; }
        public string Postal { get; set; }
        public bool PaymentMode { get; set; }
        public string PayeeName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountType { get; set; }
        public string Bank { get; set; }
        public string BranchAddress { get; set; }
        public string IFSC { get; set; }
        public string SWIFTCode { get; set; }
        public string PANNO { get; set; }
        public string TIN { get; set; }
        public string ST { get; set; }
        public string VAT { get; set; }
        public Nullable<decimal> RackRates { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocalityId { get; set; }
    
        public virtual ICollection<WRBHBPropertyAgreementsOwner> WRBHBPropertyAgreementsOwners { get; set; }
        public virtual ICollection<WRBHBPropertyOwnerApartment> WRBHBPropertyOwnerApartments { get; set; }
        public virtual ICollection<WRBHBPropertyOwnerProperty> WRBHBPropertyOwnerProperties { get; set; }
    }
}
