//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendorChequeApprovalNewDtl
    {
        public int VendorChequeApprovalHdrId { get; set; }
        public string RequestedOn { get; set; }
        public string Requestedby { get; set; }
        public decimal RequestedAmount { get; set; }
        public string Status { get; set; }
        public string Processedon { get; set; }
        public Nullable<int> RequestedUserId { get; set; }
        public string Processedby { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<bool> Process { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PropertyId { get; set; }
    }
}
