//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBContractNonDedicated
    {
        public WRBHBContractNonDedicated()
        {
            this.WRBHBContractNonDedicatedApartments = new HashSet<WRBHBContractNonDedicatedApartment>();
            this.WRBHBContractNonDedicatedServices = new HashSet<WRBHBContractNonDedicatedService>();
        }
    
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ContractType { get; set; }
        public string ContractName { get; set; }
        public string Property { get; set; }
        public long PropertyId { get; set; }
        public string Client { get; set; }
        public long ClientId { get; set; }
        public string Types { get; set; }
        public string PricingModel { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string TransName { get; set; }
        public Nullable<long> TransId { get; set; }
        public string ContractStatus { get; set; }
    
        public virtual ICollection<WRBHBContractNonDedicatedApartment> WRBHBContractNonDedicatedApartments { get; set; }
        public virtual ICollection<WRBHBContractNonDedicatedService> WRBHBContractNonDedicatedServices { get; set; }
    }
}
