//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBedBookingProperty
    {
        public long BookingId { get; set; }
        public string PropertyName { get; set; }
        public long PropertyId { get; set; }
        public string GetType { get; set; }
        public string PropertyType { get; set; }
        public decimal Tariff { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Locality { get; set; }
        public long LocalityId { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<bool> Per { get; set; }
        public Nullable<bool> Rs { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountTariff { get; set; }
    }
}
