//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBCheckInHdr
    {
        public Nullable<long> RoomId { get; set; }
        public long PropertyId { get; set; }
        public long BookingId { get; set; }
        public int StateId { get; set; }
        public int GuestId { get; set; }
        public string ChkInGuest { get; set; }
        public string CheckInNo { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public System.DateTime ChkoutDate { get; set; }
        public string RoomNo { get; set; }
        public string GuestName { get; set; }
        public string ClientName { get; set; }
        public string Property { get; set; }
        public long MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Designation { get; set; }
        public string Nationality { get; set; }
        public string IdProof { get; set; }
        public decimal ChkinAdvance { get; set; }
        public decimal Tariff { get; set; }
        public bool Direct { get; set; }
        public bool BTC { get; set; }
        public string EmpCode { get; set; }
        public string Image { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string CheckStatus { get; set; }
        public string BookingCode { get; set; }
        public Nullable<decimal> RackTariff { get; set; }
        public string TimeType { get; set; }
        public string Occupancy { get; set; }
        public Nullable<decimal> RackTariffSingle { get; set; }
        public Nullable<decimal> RackTariffDouble { get; set; }
        public Nullable<int> ApartmentId { get; set; }
        public string ApartmentType { get; set; }
        public string BedType { get; set; }
        public string BedId { get; set; }
        public string Type { get; set; }
        public string RefGuestId { get; set; }
        public string PropertyType { get; set; }
        public string GuestImage { get; set; }
        public Nullable<decimal> SingleMarkupAmount { get; set; }
        public Nullable<decimal> DoubleMarkupAmount { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ServiceCharge { get; set; }
        public string NewCheckInDate { get; set; }
        public string NewCheckoutDate { get; set; }
        public string TariffPaymentMode { get; set; }
    }
}
