//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPettyCashStatu
    {
        public int PettyCashStatusHdrId { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string ExpenseHead { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal Paid { get; set; }
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Modifiedby { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string BillLogo { get; set; }
        public int ExpenseId { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string BillDate { get; set; }
        public string BillNo { get; set; }
    }
}
