//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBTDSDeclaration
    {
        public long PropertyId { get; set; }
        public long OwnerId { get; set; }
        public string PANNO { get; set; }
        public decimal TDSPercentage { get; set; }
        public string FinancialYearId { get; set; }
        public string Image { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
