//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBAPIRoomRateDtl
    {
        public long HeaderId { get; set; }
        public string HotelId { get; set; }
        public string RoomRateroomTypeCode { get; set; }
        public string RoomRateratePlanCode { get; set; }
        public string RoomRateavailableCount { get; set; }
        public string RoomRateavailStatus { get; set; }
        public long Id { get; set; }
        public string PenaltyDescription { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
    }
}
