//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBChechkOutPaymentCompanyInvoice
    {
        public string Payment { get; set; }
        public string PayeeName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string PaymentMode { get; set; }
        public string Approver { get; set; }
        public string Requester { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public int Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<int> ChkOutHdrId { get; set; }
        public string FileLoad { get; set; }
        public Nullable<decimal> OutStanding { get; set; }
    }
}
