//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBContarctProductMaster
    {
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<bool> ContractRate { get; set; }
        public Nullable<bool> IsComplimentary { get; set; }
        public string TypeService { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public decimal PerQuantityprice { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public bool Enable { get; set; }
        public Nullable<bool> AmountChange { get; set; }
        public Nullable<int> SubTypeId { get; set; }
    }
}
