//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBReconcilePayment
    {
        public string PayType { get; set; }
        public string TransactionNo { get; set; }
        public string InvoiceNo { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> TransactionAmt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
    }
}
