//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBTaxMapping
    {
        public string Property { get; set; }
        public int PropertyId { get; set; }
        public string ServiceItem { get; set; }
        public int ItemId { get; set; }
        public bool VAT { get; set; }
        public bool LuxuryTax { get; set; }
        public bool ST1 { get; set; }
        public bool ST2 { get; set; }
        public bool ST3 { get; set; }
        public string Service { get; set; }
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Modifiedby { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
    }
}
