//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPettyCash
    {
        public int PettyCashHdrId { get; set; }
        public string Description { get; set; }
        public string ExpenseHead { get; set; }
        public decimal Amount { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ExpenseHeadId { get; set; }
    }
}
