//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBClientColumn
    {
        public long Id { get; set; }
        public long ClientId { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
        public string Column6 { get; set; }
        public string Column7 { get; set; }
        public string Column8 { get; set; }
        public string Column9 { get; set; }
        public string Column10 { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<bool> Column1Mandatory { get; set; }
        public Nullable<bool> Column2Mandatory { get; set; }
        public Nullable<bool> Column3Mandatory { get; set; }
        public Nullable<bool> Column4Mandatory { get; set; }
        public Nullable<bool> Column5Mandatory { get; set; }
        public Nullable<bool> Column6Mandatory { get; set; }
        public Nullable<bool> Column7Mandatory { get; set; }
        public Nullable<bool> Column8Mandatory { get; set; }
        public Nullable<bool> Column9Mandatory { get; set; }
        public Nullable<bool> Column10Mandatory { get; set; }
        public Nullable<bool> UpdateChkColumn1 { get; set; }
        public Nullable<bool> UpdateChkColumn2 { get; set; }
        public Nullable<bool> UpdateChkColumn3 { get; set; }
        public Nullable<bool> UpdateChkColumn4 { get; set; }
        public Nullable<bool> UpdateChkColumn5 { get; set; }
        public Nullable<bool> UpdateChkColumn6 { get; set; }
        public Nullable<bool> UpdateChkColumn7 { get; set; }
        public Nullable<bool> UpdateChkColumn8 { get; set; }
        public Nullable<bool> UpdateChkColumn9 { get; set; }
        public Nullable<bool> UpdateChkColumn10 { get; set; }
    }
}
