//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBCheckOutServiceDtl
    {
        public long CheckOutServceHdrId { get; set; }
        public bool ChkOutSerAction { get; set; }
        public bool ChkOutSerInclude { get; set; }
        public string ChkOutSerDate { get; set; }
        public string ChkOutSerItem { get; set; }
        public decimal ChkOutSerAmount { get; set; }
        public int ChkOutSerQuantity { get; set; }
        public decimal ChkOutSerNetAmount { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string TypeService { get; set; }
        public Nullable<long> ServiceHdrId { get; set; }
    }
}
