//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBScreenMaster
    {
        public int Id { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ModuleName { get; set; }
        public string SubModuleName { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> SubModuleId { get; set; }
        public string SWF { get; set; }
        public Nullable<int> CountId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
    }
}
