//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBContractManagement
    {
        public WRBHBContractManagement()
        {
            this.WRBHBContractManagementAppartments = new HashSet<WRBHBContractManagementAppartment>();
            this.WRBHBContractManagementTariffAppartments = new HashSet<WRBHBContractManagementTariffAppartment>();
        }
    
        public string Client { get; set; }
        public string ContractType { get; set; }
        public string ContractName { get; set; }
        public string Property { get; set; }
        public string BookingLevel { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ExtenstionDate { get; set; }
        public string ContractPriceMode { get; set; }
        public string RateInterval { get; set; }
        public string SalesExecutive { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public long Id { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> SalesExecutiveId { get; set; }
        public string Types { get; set; }
        public string PrintingModel { get; set; }
        public string Status { get; set; }
        public string TransubName { get; set; }
        public Nullable<long> TransubId { get; set; }
        public string ContractStatus { get; set; }
    
        public virtual ICollection<WRBHBContractManagementAppartment> WRBHBContractManagementAppartments { get; set; }
        public virtual ICollection<WRBHBContractManagementTariffAppartment> WRBHBContractManagementTariffAppartments { get; set; }
    }
}
