//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBAPITariffDtl
    {
        public long HeaderId { get; set; }
        public string HotelId { get; set; }
        public long RoomRateHdrId { get; set; }
        public string RoomTariffroomNumber { get; set; }
        public string Tarifftype { get; set; }
        public string Tariffgroup { get; set; }
        public Nullable<decimal> Tariffamount { get; set; }
        public long Id { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
    }
}
