//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBAPIRateMealPlanInclusionDtls_FrontEnd
    {
        public long HeaderId { get; set; }
        public string HotelId { get; set; }
        public string RatePlanType { get; set; }
        public string RatePlanCode { get; set; }
        public string MealPlanCode { get; set; }
        public string MealPlan { get; set; }
        public string InclusionCode { get; set; }
        public long Id { get; set; }
    }
}
