//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBDepositsDlt
    {
        public long DepHdrId { get; set; }
        public string InvoiceNo { get; set; }
        public decimal Amount { get; set; }
        public string BillType { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool Tick { get; set; }
        public System.Guid RowId { get; set; }
        public long ClientId { get; set; }
        public Nullable<long> ChkOutHdrId { get; set; }
    }
}
