//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBReconcilePaymentRef
    {
        public string InvoiceNo { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<long> ReconcilId { get; set; }
        public int thistableid { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModiafiedDate { get; set; }
    }
}
