//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBVendor
    {
        public string VendorName { get; set; }
        public string VendorCategory { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Designation { get; set; }
        public string NatureofService { get; set; }
        public string Mobile { get; set; }
        public string Office { get; set; }
        public string Email { get; set; }
        public string States { get; set; }
        public int StateId { get; set; }
        public string City { get; set; }
        public int CityId { get; set; }
        public string Website { get; set; }
        public string Addresss { get; set; }
        public Nullable<bool> PayChk { get; set; }
        public Nullable<bool> Payonline { get; set; }
        public string Bankname { get; set; }
        public string IFSCode { get; set; }
        public string Payeename { get; set; }
        public string Accountnumber { get; set; }
        public string AccountType { get; set; }
        public string Paymentcircle { get; set; }
        public string Pannum { get; set; }
        public string Saleregnumb { get; set; }
        public Nullable<System.DateTime> Saleregdate { get; set; }
        public string Servicergenum { get; set; }
        public Nullable<System.DateTime> Servicergedate { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public long CategoryId { get; set; }
        public long BankId { get; set; }
    }
}
