//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBookingTrackingPayment
    {
        public long BookingId { get; set; }
        public long BookingPropertyTableId { get; set; }
        public string RoomType { get; set; }
        public int NightStay { get; set; }
        public decimal TotalAmount { get; set; }
        public int Success { get; set; }
        public string TransactionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long Id { get; set; }
    }
}
