//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPettyCashHdr
    {
        public System.DateTime Date { get; set; }
        public int PropertyId { get; set; }
        public int UserId { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> Flag { get; set; }
        public decimal ExpenseGroupId { get; set; }
        public Nullable<int> ExpenseReport { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Modifiedby { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid RowId { get; set; }
    }
}
