//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBAPIHotelHeader
    {
        public long HeaderId { get; set; }
        public string HotelId { get; set; }
        public string StarRating { get; set; }
        public long Id { get; set; }
        public Nullable<int> HotelCount { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string InActiveRemarks { get; set; }
    }
}
