//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBBTCSubmission
    {
        public long ClientId { get; set; }
        public System.DateTime SubmittedOnDate { get; set; }
        public System.DateTime ExpectedDate { get; set; }
        public string PhysicalInvoice { get; set; }
        public string Acknowledged { get; set; }
        public string Comments { get; set; }
        public string FilePath { get; set; }
        public string CollectionStatus { get; set; }
        public int Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string FileNames { get; set; }
        public Nullable<long> BTCSubmissionId { get; set; }
        public Nullable<long> ChkOutHdrId { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<long> DepositDetilsId { get; set; }
        public string Mode { get; set; }
        public Nullable<long> ModeId { get; set; }
    }
}
