//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRBHBPropertyRoom
    {
        public WRBHBPropertyRoom()
        {
            this.WRBHBPropertyRoomBeds = new HashSet<WRBHBPropertyRoomBed>();
        }
    
        public Nullable<long> PropertyId { get; set; }
        public long BlockId { get; set; }
        public Nullable<long> ApartmentId { get; set; }
        public string RoomType { get; set; }
        public string RoomNo { get; set; }
        public decimal RackTariff { get; set; }
        public decimal DoubleOccupancyTariff { get; set; }
        public string RoomCategory { get; set; }
        public bool DiscountModePer { get; set; }
        public bool DiscountModeRS { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public long Id { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid RowId { get; set; }
        public string RoomStatus { get; set; }
        public Nullable<bool> CheckIn { get; set; }
        public Nullable<bool> CheckOut { get; set; }
    
        public virtual ICollection<WRBHBPropertyRoomBed> WRBHBPropertyRoomBeds { get; set; }
    }
}
