//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBWindowsService.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HBServiceSoap")]
    public interface HBServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Save(string type, string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Delete(string type, string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelpResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HelpResult(string type, string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchResult(string type, string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ErrorHelp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ErrorHelp(string type, string[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Checkstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Checkstatus(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HBServiceSoapChannel : HBWindowsService.ServiceReference1.HBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HBServiceSoapClient : System.ServiceModel.ClientBase<HBWindowsService.ServiceReference1.HBServiceSoap>, HBWindowsService.ServiceReference1.HBServiceSoap {
        
        public HBServiceSoapClient() {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Save(string type, string[] data) {
            return base.Channel.Save(type, data);
        }
        
        public System.Data.DataSet Delete(string type, string[] data) {
            return base.Channel.Delete(type, data);
        }
        
        public System.Data.DataSet HelpResult(string type, string[] data) {
            return base.Channel.HelpResult(type, data);
        }
        
        public System.Data.DataSet SearchResult(string type, string[] data) {
            return base.Channel.SearchResult(type, data);
        }
        
        public System.Data.DataSet ErrorHelp(string type, string[] data) {
            return base.Channel.ErrorHelp(type, data);
        }
        
        public string Checkstatus(int num) {
            return base.Channel.Checkstatus(num);
        }
    }
}
