SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[dbo].[sp_City_Delete]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1)
DROP PROCEDURE [dbo].[sp_City_Delete]
GO 
CREATE PROCEDURE [dbo].[sp_City_Delete](@Id BIGINT,@UsrId BIGINT)
AS
BEGIN 
 UPDATE WRBHBCity SET IsActive=0,IsDeleted=1,ModifiedBy=@UsrId,
 ModifiedDate=GETDATE() WHERE Id=@Id;
END